"""Independent arithmetic expectations plus fail-closed verifier checks.

The nearby split-dividend.json is a frozen fictional TypeScript export; its
hand-derived assertions below are intentionally not generated by either replay.
"""
import copy
from fractions import Fraction
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

import verify_research as v

HERE = Path(__file__).resolve().parent


def fixture(name="split-dividend"):
    return v.read_report(HERE / "fixtures" / (name + ".json"))


class IndependentResearchTests(unittest.TestCase):
    def test_split_dividend_and_signal_timing_hand_calculation(self):
        report = fixture()
        full = v.replay(report["snapshot"])["full"]
        self.assertEqual([p["value"] for p in full["strategy"]["history"]], ["120000", "120000", "112000", "112000", "112000", "134000"])
        self.assertEqual([p["value"] for p in full["buyHold"]["history"]], ["120000", "120000", "112000", "132000", "102000", "122000"])
        self.assertEqual([(t["signalDate"], t["date"], t["side"], t["shares"]) for t in full["strategy"]["trades"]], [
            ("2016-01-02", "2016-01-03", "buy", "10"),
            ("2016-01-04", "2016-01-05", "sell", "20"),
            ("2016-01-06", "2016-01-07", "buy", "22"),
            ("2016-01-07", "2016-01-08", "sell", "22"),
        ])
        self.assertEqual(full["strategy"]["history"][-1]["receivables"], "2000")
        self.assertAlmostEqual(full["strategy"]["returnPct"], 35 / 3)
        self.assertAlmostEqual(full["strategy"]["maxDrawdown"], -20 / 3)
        self.assertTrue(v.verify_report(report)["verified"])

    def test_holdout_restart_and_reverse_split(self):
        report = fixture()
        late = v.replay(report["snapshot"])["holdout"]["strategy"]
        self.assertEqual(late["history"][0], {"date": "2016-01-06", "value": "120000", "cash": "120000", "receivables": "0", "shares": "0"})
        self.assertEqual(late["trades"][0]["shares"], "24")
        self.assertEqual(late["history"][-1]["value"], "144000")
        reverse = v.replay(fixture("reverse-split")["snapshot"])["full"]["strategy"]
        self.assertEqual(reverse["trades"][1]["shares"], "10/3")
        self.assertEqual(reverse["history"][2]["receivables"], "333")
        self.assertEqual(reverse["history"][2]["shares"], "0")

    def test_fees_and_slippage_hand_calculation(self):
        report = fixture("costs")
        result = v.replay(report["snapshot"])["full"]
        self.assertEqual([(t["side"], t["shares"], t["fillMicros"], t["gross"], t["fee"]) for t in result["strategy"]["trades"]], [
            ("buy", "10", "101000000", "101000", "1010"),
            ("sell", "10", "99000000", "99000", "990"),
        ])
        self.assertEqual(result["strategy"]["history"][-1]["cash"], "98010")
        self.assertEqual(result["strategy"]["fees"], "2000")
        self.assertAlmostEqual(result["buyHold"]["maxDrawdown"], (100000 / 102010 - 1) * 100)

    def test_sizing_closed_form_against_exhaustive_affordable_choices(self):
        for cash in (1, 5, 11, 100):
            for fill in (100000000, 123456789, 1000000000, 10000000000):
                for fee_bps in (0, 17, 1000):
                    cap = int(Fraction(cash * 10**14, fill * (10000 + fee_bps)))
                    affordable = []
                    for units in range(cap + 1):
                        gross = v.half_up(Fraction(units * fill, 10**10))
                        fee = v.half_up(Fraction(gross * fee_bps, 10000))
                        if gross + fee <= cash:
                            affordable.append(units)
                    self.assertEqual(v.affordable_units(cash, fill, fee_bps), max(affordable))

    def test_risk_known_values_and_degenerate_cases(self):
        metrics = v.observed_metrics([100, 110, 99, 118.8], [100, 105, 99.75, 109.725])
        self.assertAlmostEqual(metrics["volatilityPct"], 15.27525231651947)
        self.assertAlmostEqual(metrics["sharpe"], .436435780471985)
        self.assertAlmostEqual(metrics["beta"], 2)
        self.assertAlmostEqual(metrics["correlation"], 1)
        self.assertEqual(v.observed_metrics([100, 100, 100], [100, 110, 99]), {"intervals": 2, "volatilityPct": 0.0, "sharpe": None, "beta": 0.0, "correlation": None})
        self.assertIsNone(v.observed_metrics([100, 110, 99], [100, 100, 100])["beta"])
        self.assertIsNone(v.observed_metrics([100, 110], [100, 105])["volatilityPct"])

    def test_independent_signal_basis_matches_cached_windows(self):
        for name in ("split-dividend", "reverse-split", "costs"):
            binding = fixture(name)["snapshot"]["asset"]
            for window in (2, 3, 5):
                cached = v.decision_signals(binding, window)
                for i, decision in cached.items():
                    self.assertEqual(decision, v.signal_at(binding, i, window))

    def test_all_small_canonical_exports_and_completed_service_shape(self):
        for name in ("split-dividend", "costs", "reverse-split", "separate-benchmark", "provider"):
            with self.subTest(name=name):
                report = fixture(name)
                self.assertTrue(v.verify_report(report)["verified"])
                report.update(format="marketlab-service-job-v1", status="completed")
                self.assertTrue(v.verify_report(report)["verified"])
                report["status"] = "running"
                with self.assertRaisesRegex(v.VerificationError, "completed"):
                    v.verify_report(report)

    def test_rejects_accounting_trade_metric_and_schema_tampering(self):
        mutations = [
            lambda r: r["analysis"]["full"]["strategy"]["history"][0].update(value="120001"),
            lambda r: r["analysis"]["full"]["strategy"]["history"][0].update(cash="1"),
            lambda r: r["analysis"]["full"]["strategy"]["trades"][0].update(shares="11"),
            lambda r: r["analysis"]["full"]["strategy"]["trades"][0].update(fee="1"),
            lambda r: r["analysis"]["full"]["strategy"]["trades"][0].update(signalDate="2016-01-03"),
            lambda r: r["analysis"]["full"]["strategyRisk"].update(beta=99),
            lambda r: r["analysis"]["full"]["strategyRisk"].update(beta=float("nan")),
            lambda r: r["analysis"]["full"]["strategyRisk"].update(beta=None),
            lambda r: r["analysis"]["full"].update(observations=True),
            lambda r: r["analysis"]["full"]["strategy"].update(extra="ignored?"),
        ]
        for mutate in mutations:
            with self.subTest(mutation=mutate):
                report = fixture()
                mutate(report)
                with self.assertRaises(v.VerificationError):
                    v.verify_report(report)

    def test_rejects_snapshot_and_provider_identity_tampering(self):
        report = fixture()
        report["snapshot"]["config"]["feeBps"] = 1
        with self.assertRaisesRegex(v.VerificationError, "Report ID"):
            v.verify_report(report)
        report = fixture()
        report["snapshot"]["asset"]["dataset"]["observations"][0]["priceMicros"] = "99999999"
        with self.assertRaisesRegex(v.VerificationError, "Dataset content ID"):
            v.verify_report(report)
        report = fixture("provider")
        report["snapshot"]["asset"]["dataset"]["providerTimezone"] = "UTC"
        with self.assertRaisesRegex(v.VerificationError, "Dataset content ID"):
            v.verify_report(report)

    def test_cli_success_and_actionable_failure(self):
        okay = subprocess.run([sys.executable, str(HERE / "verify_research.py"), str(HERE / "fixtures" / "split-dividend.json")], capture_output=True, text=True)
        self.assertEqual(okay.returncode, 0, okay.stderr)
        self.assertTrue(json.loads(okay.stdout)["verified"])
        with tempfile.TemporaryDirectory(prefix="marketlab-python-") as temporary:
            path = Path(temporary) / "tampered.json"
            report = fixture()
            report["analysis"]["full"]["strategy"]["fees"] = "1"
            path.write_text(json.dumps(report), encoding="utf-8")
            failed = subprocess.run([sys.executable, str(HERE / "verify_research.py"), str(path)], capture_output=True, text=True)
            self.assertEqual(failed.returncode, 1)
            self.assertIn("analysis.full.strategy.fees", failed.stderr)
            self.assertNotIn("Traceback", failed.stderr)

    def test_duplicate_nonfinite_and_oversized_json_are_rejected(self):
        with tempfile.TemporaryDirectory(prefix="marketlab-python-") as temporary:
            path = Path(temporary) / "invalid.json"
            for payload in ('{"a":1,"a":2}', '{"a":NaN}', '{"a":Infinity}', " " * (v.MAX_BYTES + 1)):
                path.write_text(payload, encoding="utf-8")
                with self.assertRaises(v.VerificationError):
                    v.read_report(path)


if __name__ == "__main__":
    unittest.main()
