// Generated by scripts/update-demo-fingerprints.ts; verified against inputs in unit tests.
// Precomputed hashes let this fixed demo run even where browser Web Crypto is unavailable.
export const DEMO_DATASET_ID = 'a9a6f3738ad120fd6006a64bab7c055eb40def39b01d81e8e64196f10e354192';
export const DEMO_RUN_IDS = {
  illustrative: '055dc42f8e88d8d636ee082e3c553a8c41f62b43edcd958289a08d24796b156c',
  higher: '8e659586b4e685d31601a67e6c8de4d1e83b9b24f52af657cdf6b9c9da94d014',
  zero: '0165cb54496901568835f389b0191df018311ec325c14378c550c86738305e9d',
} as const;
