'use client';
import ReportDownload from './report-download';
import { useEffect, useState } from 'react';
import ConfidenceCertificate from './confidence-certificate';
import { portfolioCertificate, type ConfidenceCertificate as Certificate } from '@/lib/finance/confidence';
import { Wallet, Upload, Download, Database, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { NativeSelect } from '@/components/ui/native-select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { toast } from 'sonner';
import { parseLedger, ledgerCSV, LEDGER_HEADER, type PortfolioDraft, type PortfolioAnalysis, type SavedPortfolio } from '@/lib/finance/historical-portfolio';
import type { PortfolioComparison } from '@/lib/finance/portfolio-benchmark';
import { MAX_CSV_BYTES, priceDecimal, type DatasetSummary } from '@/lib/finance/market-data';
const money=(s:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(s)/100);
const pct=(n:number)=>(n>0?'+':'')+n.toFixed(2)+'%';
type View = {portfolio:SavedPortfolio|null;analysis:PortfolioAnalysis|null;comparison:PortfolioComparison|null};
type Preview = {analysis:PortfolioAnalysis;comparison:PortfolioComparison|null;fingerprint:string;confidence:Certificate};
async function read<T>(response:Response):Promise<T>{const d=await response.json() as {error?:string};if(!response.ok)throw new Error(d.error||'Could not load the portfolio.');return d as T;}
const emptyDraft=():PortfolioDraft=>({name:'My historical portfolio',asOf:'',csv:LEDGER_HEADER+'\n',bindings:[],confirmed:false,benchmarkDatasetId:''});
function PortfolioChart({analysis,comparison}:{analysis:PortfolioAnalysis;comparison:PortfolioComparison|null}) {
  const points=analysis.history,values=[...points.flatMap(p=>[Number(p.value)/100,Number(p.contributions)/100]),...(comparison?.history.map(p=>Number(p.value)/100)??[])],lo=Math.min(...values),hi=Math.max(...values),pad=Math.max((hi-lo)*.15,1);
  const start=Date.parse(points[0].date),end=Date.parse(points.at(-1)!.date),x=(i:number)=>75+(Date.parse(points[i].date)-start)/Math.max(1,end-start)*745,y=(v:number)=>15+(hi+pad-v)/(hi-lo+2*pad)*205;
  return <div className="portfolio-chart"><div className="actions-legend"><span><i style={{background:'#20775b'}}/>Portfolio value, including receivables</span><span><i style={{background:'#929e97'}}/>Net contributions</span>{comparison&&<span><i style={{background:'#465ba9'}}/>{comparison.symbol} · matched flows, zero costs</span>}</div><svg viewBox="0 0 850 260" role="img" aria-label={`Portfolio value, net contributions${comparison?` and ${comparison.symbol} benchmark`:""} from ${points[0].date} to ${points.at(-1)!.date}; full daily values available in export.`}>
    {[0,.5,1].map(f=>{const v=lo+(hi-lo)*f;return <g key={f}><line x1="75" x2="820" y1={y(v)} y2={y(v)} stroke="#e3e9e5" strokeDasharray="3 5"/><text x="64" y={y(v)+4} textAnchor="end" fontSize="12" fill="#607367">{v.toLocaleString('en-US',{maximumFractionDigits:0})}</text></g>;})}
    {(['contributions','value'] as const).map(key=><path key={key} d={points.map((p,i)=>`${i?'L':'M'}${x(i)},${y(Number(p[key])/100)}`).join(' ')} fill="none" stroke={key==='value'?'#20775b':'#929e97'} strokeWidth="2.5" strokeDasharray={key==='value'?undefined:'6 4'}/>)}
    {comparison&&<path d={comparison.history.map((p,i)=>`${i?'L':'M'}${x(i)},${y(Number(p.value)/100)}`).join(' ')} fill="none" stroke="#465ba9" strokeWidth="2.5" strokeDasharray="8 3"/>}{points.length===1&&comparison&&<circle cx={x(0)} cy={y(Number(comparison.value)/100)} r="4" fill="#465ba9"/>}
    {points.length===1&&<circle cx={x(0)} cy={y(Number(points[0].value)/100)} r="4" fill="#20775b"/>}<text x="75" y="252" fontSize="12" fill="#607367">{points[0].date}</text>{points.length>1&&<text x="820" y="252" textAnchor="end" fontSize="12" fill="#607367">{points.at(-1)!.date}</text>}</svg></div>;
}
export default function HistoricalPortfolio({onOpenData}:{onOpenData:()=>void}) {
  const [view,setView]=useState<View|null>(null),[datasets,setDatasets]=useState<DatasetSummary[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
  const [open,setOpen]=useState(false),[draft,setDraft]=useState<PortfolioDraft>(emptyDraft),[symbols,setSymbols]=useState<string[]|null>(null),[formError,setFormError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<Preview|null>(null);
  useEffect(()=>{const controller=new AbortController();void Promise.all([fetch('/api/portfolio',{cache:'no-store',signal:controller.signal}).then(read<View>),fetch('/api/datasets',{cache:'no-store',signal:controller.signal}).then(read<{datasets:DatasetSummary[]}>)]).then(([v,d])=>{if(!controller.signal.aborted){setView(v);setDatasets(d.datasets);}}).catch(e=>{if(!controller.signal.aborted)setError((e as Error).message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[refresh]);
  function reload(){setLoading(true);setError('');setRefresh(v=>v+1);}
  function start(){const s=view?.portfolio?.snapshot;setDraft(s?{name:s.name,asOf:s.asOf,csv:ledgerCSV(s.transactions),bindings:s.bindings.map(b=>({symbol:b.dataset.symbol,datasetId:b.dataset.id})),confirmed:false,benchmarkDatasetId:s.benchmark?.binding.dataset.id??''}:emptyDraft());setSymbols(s?s.bindings.map(b=>b.dataset.symbol):null);setPreview(null);setFormError('');setOpen(true);}
  function edit(patch:Partial<PortfolioDraft>,resetRows=false){setDraft(d=>({...d,...patch,confirmed:patch.confirmed??false}));setPreview(null);setFormError('');if(resetRows)setSymbols(null);}
  async function loadFile(file?:File){if(!file)return;if(file.size>MAX_CSV_BYTES){setFormError('CSV must be 256 KiB or smaller.');return;}setBusy(true);try{edit({csv:await file.text()},true);}catch{setFormError('Could not read the CSV.');}finally{setBusy(false);}}
  function readLedger(){try{const tx=parseLedger(draft.csv,draft.asOf),next=[...new Set(tx.filter(t=>t.symbol).map(t=>t.symbol))].sort();if(next.length>10)throw new Error('Use at most ten symbols.');setSymbols(next);setDraft(d=>({...d,bindings:next.map(symbol=>({symbol,datasetId:d.bindings.find(b=>b.symbol===symbol)?.datasetId??''})),confirmed:false}));setPreview(null);setFormError('');}catch(e){setFormError((e as Error).message);}}
  async function submit(mode:'preview'|'save'){setBusy(true);setFormError('');try{const response=await fetch('/api/portfolio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,revision:view?.portfolio?.revision??0,fingerprint:preview?.fingerprint,draft})});if(mode==='preview')setPreview(await read<Preview>(response));else{const result=await read<View&{message:string}>(response);setView(result);setOpen(false);toast.success(result.message);}}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
  const p=view?.portfolio,a=view?.analysis,b=view?.comparison??null;
  return <div className="research-workspace">
    {error&&<div className="error-banner" role="alert">{error}<button onClick={reload}>Retry</button></div>}
    {loading?<div className="panel empty-state" role="status">Loading your historical portfolio…</div>:!p&&!error?<section className="panel research-empty"><Wallet size={36}/><h2>Your portfolio starts empty.</h2><p>Import a complete USD transaction ledger and connect each holding to your saved daily prices.</p><div><Button onClick={start}><Upload size={16}/> Import transactions</Button><Button variant="outline" onClick={onOpenData}><Database size={16}/> Prepare historical data</Button></div><p className="research-muted">Start with cash funding. Each stock needs unadjusted prices and a saved split/dividend coverage record. No sample trades are added.</p></section>:null}
    {p&&a&&!loading&&<>
      <div className="portfolio-toolbar"><div><h2>{p.snapshot.name}</h2><p>As of {p.snapshot.asOf} · Revision {p.revision} · {a.synthetic?'Contains fictional price inputs':'User-supplied historical portfolio'}</p></div><div><Button variant="outline" asChild><ReportDownload href="/api/portfolio?download=1" download><Download size={16}/> Full report JSON</ReportDownload></Button><Button variant="outline" asChild><ReportDownload href="/api/portfolio?download=csv" download>Observations CSV</ReportDownload></Button><Button onClick={start}><Upload size={16}/> Edit portfolio</Button></div></div>
      <ConfidenceCertificate certificate={portfolioCertificate(p.snapshot,a,b,p.fingerprint)}/>
      <div className="portfolio-metrics"><div><span>Total value</span><strong>{money(a.value)}</strong><small>Holdings + cash + receivables</small></div><div><span>Net contributions</span><strong>{money(a.contributions)}</strong><small>Deposits less withdrawals</small></div><div><span>Investment gain</span><strong className={BigInt(a.gain)>=0n?'positive':'negative'}>{money(a.gain)}</strong><small>Includes fees and earned dividends</small></div><div><span>Time-weighted return</span><strong>{pct(a.returnPct)}</strong><small>Daily close convention</small></div><div><span>Spendable cash</span><strong>{money(a.cash)}</strong><small>Cash movements as recorded</small></div><div><span>Unpaid dividends</span><strong>{money(a.receivables)}</strong><small>Earned; awaiting payment entry</small></div></div>
      <section className="panel"><div className="panel-heading"><div><h2>Portfolio value</h2><p>{a.history.length} valuation dates · exact-date prices</p></div><span className="research-kind">{(b?.synthetic??a.synthetic)?'SYNTHETIC INPUTS':'HISTORICAL RESEARCH'}</span></div><PortfolioChart analysis={a} comparison={b}/><div className="research-chart-note">External contributions are separated from performance. Observed return drawdown: {pct(a.maxDrawdown)}. Lines connect valued dates; missing sessions are not inferred.</div></section>
      {b?<section className="panel portfolio-benchmark"><div className="panel-heading"><div><h2>Same deposits. Same withdrawals.</h2><p>Your recorded portfolio versus a hypothetical {b.symbol} holding.</p></div><span className="research-kind">{b.synthetic?'SYNTHETIC COMPARISON':'CASH-FLOW MATCHED'}</span></div>
        <div className="benchmark-highlights"><div><span>Portfolio minus benchmark</span><strong className={BigInt(b.valueDifference)>=0n?'positive':'negative'}>{money(b.valueDifference)}</strong><small>Ending wealth difference in USD</small></div><div><span>Time-weighted return difference</span><strong className={b.returnDifferencePp>=0?'positive':'negative'}>{b.returnDifferencePp>0?'+':''}{b.returnDifferencePp.toFixed(2)} pp</strong><small>Portfolio return minus benchmark return</small></div></div>
        <Table><TableHeader><TableRow><TableHead>Measure</TableHead><TableHead className="numeric">Your portfolio</TableHead><TableHead className="numeric">{b.symbol} · zero costs</TableHead></TableRow></TableHeader><TableBody>
          <TableRow><TableCell>Ending value</TableCell><TableCell className="numeric">{money(a.value)}</TableCell><TableCell className="numeric">{money(b.value)}</TableCell></TableRow>
          <TableRow><TableCell>Net contributions</TableCell><TableCell className="numeric">{money(a.contributions)}</TableCell><TableCell className="numeric">{money(b.contributions)}</TableCell></TableRow>
          <TableRow><TableCell>Gain after external flows</TableCell><TableCell className="numeric">{money(a.gain)}</TableCell><TableCell className="numeric">{money(b.gain)}</TableCell></TableRow>
          <TableRow><TableCell>Time-weighted return</TableCell><TableCell className="numeric">{pct(a.returnPct)}</TableCell><TableCell className="numeric">{pct(b.returnPct)}</TableCell></TableRow>
          <TableRow><TableCell>Observed return drawdown</TableCell><TableCell className="numeric">{pct(a.maxDrawdown)}</TableCell><TableCell className="numeric">{pct(b.maxDrawdown)}</TableCell></TableRow>
          <TableRow><TableCell>Unpaid dividends</TableCell><TableCell className="numeric">{money(a.receivables)}</TableCell><TableCell className="numeric">{money(b.receivables)}</TableCell></TableRow>
        </TableBody></Table><div className="research-chart-note">The benchmark invests each deposit and sells shares for each withdrawal at the same date’s close. It uses ideal fractional shares and <strong>zero fees or slippage</strong>; your portfolio includes recorded costs. Benchmark dividends remain unpaid receivables and are never reinvested or spent. Comparison uses the {b.history.length} portfolio valuation dates, with no missing-price substitution. This is a modeled holding, not an official total-return index.</div></section>:<section className="panel portfolio-benchmark-empty"><div><h2>Compare the same cash flows</h2><p>Choose saved benchmark prices to see how the same deposits and withdrawals would have performed.</p></div><Button variant="outline" onClick={start}>Add benchmark</Button></section>}
      <section className="panel"><div className="panel-heading"><h2>Holdings</h2><span className="subtle">Cost basis includes purchase fees</span></div>{a.holdings.length?<Table><TableHeader><TableRow><TableHead>Symbol</TableHead><TableHead className="numeric">Shares</TableHead><TableHead className="numeric">Close (USD)</TableHead><TableHead className="numeric">Value</TableHead><TableHead className="numeric">Cost basis</TableHead><TableHead className="numeric">Unrealized gain</TableHead></TableRow></TableHeader><TableBody>{a.holdings.map(h=><TableRow key={h.symbol}><TableCell>{h.symbol}</TableCell><TableCell className="numeric">{h.shares}</TableCell><TableCell className="numeric">{priceDecimal(h.priceMicros)}</TableCell><TableCell className="numeric">{money(h.value)}</TableCell><TableCell className="numeric">{money(h.cost)}</TableCell><TableCell className="numeric">{money(h.gain)}</TableCell></TableRow>)}</TableBody></Table>:<p className="actions-message">No open stock positions. Cash and unpaid entitlements remain in total value.</p>}</section>
      <section className="panel portfolio-reconciliation"><div className="panel-heading"><h2><ShieldCheck size={18}/> Gain reconciliation</h2><span className="research-kind">RECONCILED</span></div><div className="portfolio-equation"><span>Realized <strong>{money(a.realized)}</strong></span><b>+</b><span>Unrealized <strong>{money(a.unrealized)}</strong></span><b>+</b><span>Dividends earned <strong>{money(a.income)}</strong></span><b>=</b><span>Total gain <strong>{money(a.gain)}</strong></span></div><p>Trading fees of {money(a.fees)} are already included in cost and realized gain. Dividend payments move value from receivables to cash without earning it twice.</p></section>
      {a.dividends.length>0&&<section className="panel"><div className="panel-heading"><h2>Dividend entitlements</h2><span className="subtle">Eligibility fixed before ex-date trades</span></div><Table><TableHeader><TableRow><TableHead>Symbol</TableHead><TableHead>Ex-date</TableHead><TableHead className="numeric">Earned</TableHead><TableHead>Payment recorded</TableHead></TableRow></TableHeader><TableBody>{a.dividends.map(d=><TableRow key={`${d.symbol}:${d.exDate}`}><TableCell>{d.symbol}</TableCell><TableCell>{d.exDate}</TableCell><TableCell className="numeric">{money(d.earned)}</TableCell><TableCell>{d.paidDate??'Unpaid'}</TableCell></TableRow>)}</TableBody></Table></section>}
      <section className="panel research-provenance"><div className="panel-heading"><h2><Database size={18}/> Frozen research inputs</h2><Button variant="outline" onClick={onOpenData}>Historical data</Button></div><div className="portfolio-inputs">{p.snapshot.bindings.length?p.snapshot.bindings.map(b=><div key={b.dataset.id}><strong>{b.dataset.symbol} · {b.dataset.source}</strong><p>{b.dataset.firstDate} → {b.dataset.lastDate} · {b.dataset.count} observations · {b.dataset.kind==='synthetic'?'Fictional':'Historical'} · USD</p><p>Event source: {b.actions.source} · Revision {b.actions.revision} · {b.actions.events.length} events</p><code>{b.dataset.id}</code></div>):<p>Cash-only ledger; no market-price inputs.</p>}{p.snapshot.benchmark&&<div><strong>Benchmark · {p.snapshot.benchmark.binding.dataset.symbol} · {p.snapshot.benchmark.binding.dataset.source}</strong><p>{p.snapshot.benchmark.binding.dataset.firstDate} → {p.snapshot.benchmark.binding.dataset.lastDate} · {p.snapshot.benchmark.binding.dataset.kind==='synthetic'?'Fictional':'Historical'} · USD</p><p>Event source: {p.snapshot.benchmark.binding.actions.source} · Revision {p.snapshot.benchmark.binding.actions.revision}</p><code>{p.snapshot.benchmark.binding.dataset.id}</code><code>{p.snapshot.benchmark.method}</code></div>}<p>Price observations and the complete event records are saved with this portfolio. Later edits in Historical data do not alter this result. Updating the ledger previews and pins the currently selected records again.</p><code>Portfolio fingerprint: {p.fingerprint}</code></div></section>
      <section className="panel"><div className="panel-heading"><h2>Imported transactions</h2><span className="subtle">Latest {Math.min(20,p.snapshot.transactions.length)} of {p.snapshot.transactions.length} · full ledger in export</span></div><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>ID / type</TableHead><TableHead>Symbol</TableHead><TableHead className="numeric">Shares</TableHead><TableHead className="numeric">Gross amount</TableHead><TableHead className="numeric">Fee</TableHead></TableRow></TableHeader><TableBody>{p.snapshot.transactions.slice(-20).reverse().map(t=><TableRow key={t.id}><TableCell>{t.date}</TableCell><TableCell>{t.type.replaceAll('_',' ')}<small className="cell-small">{t.id}{t.reference&&` · ex-date ${t.reference}`}</small></TableCell><TableCell>{t.symbol||'USD'}</TableCell><TableCell className="numeric">{Number(t.units)/1e6||'—'}</TableCell><TableCell className="numeric">{money(t.amount)}</TableCell><TableCell className="numeric">{money(t.fee)}</TableCell></TableRow>)}</TableBody></Table></section>
      <p className="portfolio-method">Research conventions: starts in cash; trades execute at the daily closing mark in CSV order, using your recorded gross amount and fees. Splits and dividend entitlements apply before that day’s trades. Fractional split shares are retained exactly. No shorting, borrowing, tax-lot accounting, cash in lieu, spin-offs or other unsupported distributions. Instrument identity and event completeness are declared by you.</p>
    </>}
    <Dialog open={open} onOpenChange={value=>{if(!busy){setOpen(value);if(!value)reload();}}}><DialogContent className="import-dialog portfolio-dialog"><DialogHeader><DialogTitle>{p?'Update historical portfolio':'Import your portfolio'}</DialogTitle><DialogDescription>Import the complete ledger from cash funding. Preview and reconcile before saving. {p?'Saving replaces the current ledger; export it first if you need the old revision.':''}</DialogDescription></DialogHeader>
      <form className="import-form" onSubmit={e=>{e.preventDefault();void submit('preview');}}><fieldset className="import-fields" disabled={busy}>
        <div className="form-grid"><label>Portfolio name<Input value={draft.name} onChange={e=>edit({name:e.target.value})} minLength={2} maxLength={80} required/></label><label>Valuation date<Input type="date" value={draft.asOf} required onInput={e=>edit({asOf:e.currentTarget.value},true)}/></label></div>
        <label>Upload transaction CSV<Input type="file" accept=".csv,text/csv" onChange={e=>{void loadFile(e.target.files?.[0]);e.target.value='';}}/></label><label>Complete ledger CSV<Textarea aria-label="Complete ledger CSV" value={draft.csv} onChange={e=>edit({csv:e.target.value},true)} rows={7} maxLength={MAX_CSV_BYTES} required/></label>
        <div className="portfolio-csv-help"><code>{LEDGER_HEADER}</code><p>Types: deposit, withdrawal, buy, sell, dividend_payment. Amount is the <strong>gross USD amount</strong>, not the share price; fee is separate. Use unique IDs. Cash flows leave symbol/reference empty. Dividend payments reference their ex-date (YYYY-MM-DD) and must match the earned entitlement.</p><p>Example cash funding row: <code>fund-1,2026-09-14,deposit,,0,1000,0,</code></p><p>Maximum 500 rows and 10 symbols. Same-date rows execute in file order. Start from cash; opening stock positions and incomplete trade histories are unsupported.</p></div>
        <Button type="button" variant="outline" onClick={readLedger}>Read ledger & map symbols</Button>
        {symbols!==null&&<><div className="portfolio-mappings">{symbols.length?symbols.map(symbol=><label key={symbol}>{symbol} price dataset<NativeSelect value={draft.bindings.find(b=>b.symbol===symbol)?.datasetId??''} required onChange={e=>edit({bindings:draft.bindings.map(b=>b.symbol===symbol?{...b,datasetId:e.target.value}:b)})}><option value="">Select saved unadjusted prices</option>{datasets.filter(d=>d.symbol===symbol&&d.basis==='raw'&&d.priceColumn==='close').map(d=><option key={d.id} value={d.id}>{d.symbol} · {d.firstDate} → {d.lastDate} · {d.kind==='synthetic'?'Fictional':'Historical'} · {d.id.slice(0,8)}</option>)}</NativeSelect></label>):<p className="form-note">Cash-only ledger: no symbol mapping is needed.</p>}</div><p className="form-note">Each selected dataset needs a saved, complete split/dividend record in Historical data. Confirm the ticker refers to the same USD instrument throughout the period. Exact-date closes are required for every held asset at every valuation date; missing marks stop the preview.</p><label>Cash-flow benchmark (optional)<NativeSelect aria-label="Cash-flow benchmark" value={draft.benchmarkDatasetId??''} onChange={e=>edit({benchmarkDatasetId:e.target.value})}><option value="">No benchmark comparison</option>{datasets.filter(d=>d.basis==='raw'&&d.priceColumn==='close').map(d=><option key={d.id} value={d.id}>{d.symbol} · {d.firstDate} → {d.lastDate} · {d.kind==='synthetic'?'Fictional':'Historical'} · {d.id.slice(0,8)}</option>)}</NativeSelect></label><p className="form-note">Use a USD instrument with exact closes for every portfolio valuation date and a complete event record. The benchmark matches external flows, assumes zero trading costs, and holds dividends as unpaid receivables. A withdrawal it cannot fund stops the comparison.</p><label className="actions-confirm"><Checkbox checked={draft.confirmed} onCheckedChange={value=>edit({confirmed:value===true})}/><span>I checked that the ledger is complete from cash funding and each dataset matches the same instrument and USD currency.</span></label></>}
      </fieldset>{formError&&<p className="negative import-error" role="alert">{formError}</p>}{preview&&<div className="import-preview"><strong>Reconciled preview · not saved yet</strong><p>Value {money(preview.analysis.value)} · Gain {money(preview.analysis.gain)} · Return {pct(preview.analysis.returnPct)}</p><p>Spendable cash {money(preview.analysis.cash)} · Unpaid dividends {money(preview.analysis.receivables)}</p>{preview.comparison&&<p>Benchmark {preview.comparison.symbol}: {money(preview.comparison.value)} · Your portfolio minus benchmark: {money(preview.comparison.valueDifference)} · Zero benchmark trading costs</p>}<small>{(preview.comparison?.synthetic??preview.analysis.synthetic)?'Contains fictional price inputs.':'Historical inputs and mappings are user-supplied.'} Prices and event records will be frozen with this portfolio.</small></div>}{preview&&<ConfidenceCertificate certificate={preview.confidence}/>}<div className="import-actions"><Button type="submit" variant={preview?'outline':'default'} disabled={busy||symbols===null}>{busy?'Checking…':'Validate & preview portfolio'}</Button>{preview&&<Button type="button" onClick={()=>void submit('save')} disabled={busy}>Save portfolio</Button>}</div></form>
    </DialogContent></Dialog>
  </div>;
}
