'use client';
import MetricLabel from './metric-label';
import { friendlyError } from '@/lib/client-errors';
import ReportDownload from './report-download';
import { useEffect, useState } from 'react';
import ConfidenceCertificate from './confidence-certificate';
import BrokerageReceiptView from './brokerage-receipt';
import { portfolioCertificate, type ConfidenceCertificate as Certificate } from '@/lib/finance/confidence';
import { Wallet, Upload, Download, Database, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { NativeSelect } from '@/components/ui/native-select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { toast } from 'sonner';
import { readPortfolioCSV, ledgerCSV, LEDGER_HEADER, type PortfolioDraft, type PortfolioAnalysis, type SavedPortfolio } from '@/lib/finance/historical-portfolio';
import { detectPortfolioFormat, SCHWAB_FORMAT, type BrokerageImport, type BrokerageKind, type BrokerageOrder } from '@/lib/finance/brokerage-csv';
import type { PortfolioComparison } from '@/lib/finance/portfolio-benchmark';
import { MAX_CSV_BYTES, priceDecimal, type DatasetSummary } from '@/lib/finance/market-data';
import { practicePrices, practiceActions, practiceDraft } from '@/lib/practice-portfolio';
const money=(s:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(s)/100);
const pct=(n:number)=>(n>0?'+':'')+n.toFixed(2)+'%';
type View = {portfolio:SavedPortfolio|null;analysis:PortfolioAnalysis|null;comparison:PortfolioComparison|null};
type Preview = {analysis:PortfolioAnalysis;comparison:PortfolioComparison|null;fingerprint:string;confidence:Certificate};
async function read<T>(response:Response):Promise<T>{const d=await response.json() as {error?:string};if(!response.ok)throw new Error(d.error||'Could not load the portfolio.');return d as T;}
const emptyDraft=():PortfolioDraft=>({name:'My portfolio',asOf:'',csv:'',bindings:[],confirmed:false,benchmarkDatasetId:'',importFormat:SCHWAB_FORMAT,brokerageOrder:'newest-first',brokerageKind:'historical'});
function PortfolioChart({analysis,comparison}:{analysis:PortfolioAnalysis;comparison:PortfolioComparison|null}) {
  const points=analysis.history,values=[...points.flatMap(p=>[Number(p.value)/100,Number(p.contributions)/100]),...(comparison?.history.map(p=>Number(p.value)/100)??[])],lo=Math.min(...values),hi=Math.max(...values),pad=Math.max((hi-lo)*.15,1);
  const start=Date.parse(points[0].date),end=Date.parse(points.at(-1)!.date),x=(i:number)=>75+(Date.parse(points[i].date)-start)/Math.max(1,end-start)*745,y=(v:number)=>15+(hi+pad-v)/(hi-lo+2*pad)*205;
  return <div className="portfolio-chart"><div className="actions-legend"><span><i style={{background:'#20775b'}}/>Portfolio value, including earned dividends</span><span><i style={{background:'#929e97'}}/>Net contributions</span>{comparison&&<span><i style={{background:'#465ba9'}}/>{comparison.symbol} · matched flows, zero costs</span>}</div><svg viewBox="0 0 850 260" role="img" aria-label={`Portfolio value, net contributions${comparison?` and ${comparison.symbol} benchmark`:""} from ${points[0].date} to ${points.at(-1)!.date}; full daily values available in export.`}>
    {[0,.5,1].map(f=>{const v=lo+(hi-lo)*f;return <g key={f}><line x1="75" x2="820" y1={y(v)} y2={y(v)} stroke="#e3e9e5" strokeDasharray="3 5"/><text x="64" y={y(v)+4} textAnchor="end" fontSize="12" fill="#607367">{v.toLocaleString('en-US',{maximumFractionDigits:0})}</text></g>;})}
    {(['contributions','value'] as const).map(key=><path key={key} d={points.map((p,i)=>`${i?'L':'M'}${x(i)},${y(Number(p[key])/100)}`).join(' ')} fill="none" stroke={key==='value'?'#20775b':'#929e97'} strokeWidth="2.5" strokeDasharray={key==='value'?undefined:'6 4'}/>)}
    {comparison&&<path d={comparison.history.map((p,i)=>`${i?'L':'M'}${x(i)},${y(Number(p.value)/100)}`).join(' ')} fill="none" stroke="#465ba9" strokeWidth="2.5" strokeDasharray="8 3"/>}{points.length===1&&comparison&&<circle cx={x(0)} cy={y(Number(comparison.value)/100)} r="4" fill="#465ba9"/>}
    {points.length===1&&<circle cx={x(0)} cy={y(Number(points[0].value)/100)} r="4" fill="#20775b"/>}<text x="75" y="252" fontSize="12" fill="#607367">{points[0].date}</text>{points.length>1&&<text x="820" y="252" textAnchor="end" fontSize="12" fill="#607367">{points.at(-1)!.date}</text>}</svg></div>;
}
export default function HistoricalPortfolio({onOpenData}:{onOpenData:()=>void}) {
  const [practiceOpen,setPracticeOpen]=useState(false);
  const [view,setView]=useState<View|null>(null),[datasets,setDatasets]=useState<DatasetSummary[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
  const [open,setOpen]=useState(false),[draft,setDraft]=useState<PortfolioDraft>(emptyDraft),[symbols,setSymbols]=useState<string[]|null>(null),[formError,setFormError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<Preview|null>(null);
  const [brokerageReview,setBrokerageReview]=useState<BrokerageImport|null>(null);
  useEffect(()=>{const controller=new AbortController();void Promise.all([fetch('/api/portfolio',{cache:'no-store',signal:controller.signal}).then(read<View>),fetch('/api/datasets',{cache:'no-store',signal:controller.signal}).then(read<{datasets:DatasetSummary[]}>)]).then(([v,d])=>{if(!controller.signal.aborted){setView(v);setDatasets(d.datasets);}}).catch(e=>{if(!controller.signal.aborted)setError(friendlyError(e));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[refresh]);
  function reload(){setLoading(true);setError('');setRefresh(v=>v+1);}
  function start(){const s=view?.portfolio?.snapshot;setDraft(s?{name:s.name,asOf:s.asOf,csv:ledgerCSV(s.transactions),bindings:s.bindings.map(b=>({symbol:b.dataset.symbol,datasetId:b.dataset.id})),confirmed:false,benchmarkDatasetId:s.benchmark?.binding.dataset.id??''}:emptyDraft());setSymbols(s?s.bindings.map(b=>b.dataset.symbol):null);setBrokerageReview(null);setPreview(null);setFormError('');setOpen(true);}
  function edit(patch:Partial<PortfolioDraft>,resetRows=false){setDraft(d=>({...d,...patch,confirmed:patch.confirmed??false}));setPreview(null);setFormError('');if(resetRows){setSymbols(null);setBrokerageReview(null);}}
  function inspect(nextDraft:PortfolioDraft){
    const parsed=readPortfolioCSV(nextDraft),next=[...new Set(parsed.transactions.filter(t=>t.symbol).map(t=>t.symbol))].sort();
    if(next.length>10)throw new Error('Use at most ten symbols.');
    const bindings=next.map(symbol=>{const eligible=datasets.filter(d=>d.symbol===symbol&&d.basis==='raw'&&d.priceColumn==='close');return {symbol,datasetId:nextDraft.bindings.find(b=>b.symbol===symbol)?.datasetId??(eligible[0]?.id??'')};});
    setSymbols(next);setDraft({...nextDraft,bindings,confirmed:false});setBrokerageReview(parsed.importReceipt?{transactions:parsed.transactions,receipt:parsed.importReceipt}:null);setPreview(null);setFormError('');
    return parsed;
  }
  function acceptCSV(csv:string,kind:BrokerageKind,example=false){
    setSymbols(null);setBrokerageReview(null);setPreview(null);setFormError('');
    const importFormat=detectPortfolioFormat(csv),isBroker=importFormat===SCHWAB_FORMAT;
    const next:PortfolioDraft={...draft,csv,importFormat,asOf:example?'2026-09-18':draft.asOf||new Date().toISOString().slice(0,10),name:example?'Fictional Schwab import':draft.name,benchmarkDatasetId:example?'':draft.benchmarkDatasetId,brokerageOrder:isBroker?'newest-first':undefined,brokerageKind:isBroker?kind:undefined,confirmed:false};
    setDraft(next);
    const parsed=inspect(next);
    if(!draft.asOf&&!example)setDraft(d=>({...d,asOf:parsed.transactions.at(-1)!.date}));
  }
  async function loadFile(file?:File){if(!file)return;setPreview(null);setSymbols(null);setBrokerageReview(null);if(file.size>MAX_CSV_BYTES){setFormError('This file is too large. Choose a CSV smaller than 256 KB.');return;}setBusy(true);try{acceptCSV(await file.text(),'historical');}catch(e){setFormError(friendlyError(e)||'Could not read the CSV.');}finally{setBusy(false);}}
  async function loadExample(){setBusy(true);setPreview(null);setSymbols(null);setBrokerageReview(null);setFormError('');try{const response=await fetch('/examples/schwab-transactions.csv');if(!response.ok)throw new Error('Could not load the fictional file.');acceptCSV(await response.text(),'synthetic',true);}catch(e){setFormError(friendlyError(e));}finally{setBusy(false);}}
  function readLedger(){setPreview(null);setSymbols(null);setBrokerageReview(null);try{inspect(draft);}catch(e){setFormError(friendlyError(e));}}
  async function submit(mode:'preview'|'save'){setBusy(true);setFormError('');try{const response=await fetch('/api/portfolio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,revision:view?.portfolio?.revision??0,fingerprint:preview?.fingerprint,draft})});if(mode==='preview')setPreview(await read<Preview>(response));else{const result=await read<View&{message:string}>(response);setView(result);setOpen(false);setPracticeOpen(false);toast.success('Your portfolio is saved.');}}catch(e){setFormError(friendlyError(e));}finally{setBusy(false);}}
  async function tryPractice(){
    setPracticeOpen(true);setBusy(true);setPreview(null);setFormError('');
    const post=async<T,>(url:string,body:unknown)=>read<T>(await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));
    try {
      const file=await fetch('/examples/schwab-transactions.csv');if(!file.ok)throw new Error('Could not load the fictional file.');const csv=await file.text();
      const saved=await post<{dataset:DatasetSummary}>('/api/datasets',practicePrices);
      const existing=await read<{actions:{source:string;events:unknown[]}|null}>(await fetch('/api/actions?id='+saved.dataset.id));
      if(!existing.actions)await post('/api/actions',{datasetId:saved.dataset.id,revision:0,actions:practiceActions});
      else if(existing.actions.source!==practiceActions.source||existing.actions.events.length)throw new Error('This practice price history was edited. Import transactions to review your changes.');
      const next=practiceDraft(csv,saved.dataset.id);setDraft(next);setSymbols(['XDEMO']);setDatasets(ds=>[saved.dataset,...ds.filter(d=>d.id!==saved.dataset.id)]);
      setPreview(await post<Preview>('/api/portfolio',{mode:'preview',revision:0,draft:next}));
    }catch(e){setFormError(friendlyError(e));}finally{setBusy(false);}
  }
  const p=view?.portfolio,a=view?.analysis,b=view?.comparison??null,isBroker=draft.importFormat===SCHWAB_FORMAT;
  return <div className="research-workspace">
    {error&&<div className="error-banner" role="alert">{error}<button onClick={reload}>Retry</button></div>}
    {loading?<div className="panel empty-state" role="status">Loading your portfolio…</div>:!p&&!error?<section className="panel research-empty"><Wallet size={36}/><h2>Your workspace is ready.</h2><p>Upload your Schwab transaction history to see your holdings, growth, and trading costs. Your portfolio is saved to your account.</p><div><Button onClick={start}><Upload size={16}/> Import transactions</Button><Button variant="outline" onClick={()=>void tryPractice()} disabled={busy}>Try a practice portfolio</Button></div><p className="research-muted">The practice portfolio uses fictional transactions and prices. No files needed.</p></section>:null}
    {p&&a&&!loading&&<>
      <div className="portfolio-toolbar"><div><h2>{p.snapshot.name}</h2><p>As of {p.snapshot.asOf} · {a.synthetic?'Fictional example':'Your saved portfolio'}</p></div><div><details className="export-menu"><summary>Download report</summary><Button variant="outline" asChild><ReportDownload href="/api/portfolio?download=1" download><Download size={16}/> Full report JSON</ReportDownload></Button><Button variant="outline" asChild><ReportDownload href="/api/portfolio?download=csv" download>Spreadsheet (CSV)</ReportDownload></Button></details><Button onClick={start}><Upload size={16}/> Edit portfolio</Button></div></div>
      <ConfidenceCertificate certificate={portfolioCertificate(p.snapshot,a,b,p.fingerprint)}/>
      {p.snapshot.importReceipt&&<details className="product-details"><summary>Import details</summary><BrokerageReceiptView receipt={p.snapshot.importReceipt} transactions={p.snapshot.transactions} saved/></details>}
      <div className="portfolio-metrics"><div><span>Total value</span><strong>{money(a.value)}</strong><small>Investments, cash, and earned dividends</small></div><div><MetricLabel>Net contributions</MetricLabel><strong>{money(a.contributions)}</strong><small>Deposits less withdrawals</small></div><div><MetricLabel>Investment gain</MetricLabel><strong className={BigInt(a.gain)>=0n?'positive':'negative'}>{money(a.gain)}</strong><small>Includes fees and earned dividends</small></div><div><MetricLabel>Time-weighted return</MetricLabel><strong>{pct(a.returnPct)}</strong><small>Growth with deposits and withdrawals removed</small></div><div><span>Spendable cash</span><strong>{money(a.cash)}</strong><small>Money available to invest</small></div><div><span>Unpaid dividends</span><strong>{money(a.receivables)}</strong><small>Dividends earned but not yet received</small></div></div>
      <section className="panel"><div className="panel-heading"><div><h2>Portfolio value</h2><p>{a.history.length} valuation dates with closing prices</p></div><span className="research-kind">{(b?.synthetic??a.synthetic)?'FICTIONAL EXAMPLE':'YOUR PORTFOLIO'}</span></div><PortfolioChart analysis={a} comparison={b}/><div className="research-chart-note">Investment growth is shown separately from the money you added. The largest drop from an earlier high was {pct(a.maxDrawdown)}.</div></section>
      {b?<section className="panel portfolio-benchmark"><div className="panel-heading"><div><h2>Same deposits. Same withdrawals.</h2><p>Your recorded portfolio versus a hypothetical {b.symbol} holding.</p></div><span className="research-kind">{b.synthetic?'SYNTHETIC COMPARISON':'CASH-FLOW MATCHED'}</span></div>
        <div className="benchmark-highlights"><div><span>Portfolio minus benchmark</span><strong className={BigInt(b.valueDifference)>=0n?'positive':'negative'}>{money(b.valueDifference)}</strong><small>Ending wealth difference in USD</small></div><div><span>Time-weighted return difference</span><strong className={b.returnDifferencePp>=0?'positive':'negative'}>{b.returnDifferencePp>0?'+':''}{b.returnDifferencePp.toFixed(2)} pp</strong><small>Portfolio return minus benchmark return</small></div></div>
        <Table><TableHeader><TableRow><TableHead>Measure</TableHead><TableHead className="numeric">Your portfolio</TableHead><TableHead className="numeric">{b.symbol} · zero costs</TableHead></TableRow></TableHeader><TableBody>
          <TableRow><TableCell><MetricLabel>Ending value</MetricLabel></TableCell><TableCell className="numeric">{money(a.value)}</TableCell><TableCell className="numeric">{money(b.value)}</TableCell></TableRow>
          <TableRow><TableCell><MetricLabel>Net contributions</MetricLabel></TableCell><TableCell className="numeric">{money(a.contributions)}</TableCell><TableCell className="numeric">{money(b.contributions)}</TableCell></TableRow>
          <TableRow><TableCell><MetricLabel>Investment gain</MetricLabel></TableCell><TableCell className="numeric">{money(a.gain)}</TableCell><TableCell className="numeric">{money(b.gain)}</TableCell></TableRow>
          <TableRow><TableCell><MetricLabel>Time-weighted return</MetricLabel></TableCell><TableCell className="numeric">{pct(a.returnPct)}</TableCell><TableCell className="numeric">{pct(b.returnPct)}</TableCell></TableRow>
          <TableRow><TableCell><MetricLabel>Drawdown</MetricLabel></TableCell><TableCell className="numeric">{pct(a.maxDrawdown)}</TableCell><TableCell className="numeric">{pct(b.maxDrawdown)}</TableCell></TableRow>
          <TableRow><TableCell>Unpaid dividends</TableCell><TableCell className="numeric">{money(a.receivables)}</TableCell><TableCell className="numeric">{money(b.receivables)}</TableCell></TableRow>
        </TableBody></Table><div className="research-chart-note">The benchmark invests each deposit and sells shares for each withdrawal at the same date’s close. It uses ideal fractional shares and <strong>zero fees or slippage</strong>; your portfolio includes recorded costs. Benchmark dividends remain unpaid receivables and are never reinvested or spent. Comparison uses the {b.history.length} portfolio valuation dates, with no missing-price substitution. This is a modeled holding, not an official total-return index.</div></section>:<section className="panel portfolio-benchmark-empty"><div><h2>Compare the same cash flows</h2><p>Choose saved benchmark prices to see how the same deposits and withdrawals would have performed.</p></div><Button variant="outline" onClick={start}>Add benchmark</Button></section>}
      <section className="panel"><div className="panel-heading"><h2>Holdings</h2><span className="subtle">Cost basis includes purchase fees</span></div>{a.holdings.length?<Table><TableHeader><TableRow><TableHead>Symbol</TableHead><TableHead className="numeric">Shares</TableHead><TableHead className="numeric"><MetricLabel>Close (USD)</MetricLabel></TableHead><TableHead className="numeric">Value</TableHead><TableHead className="numeric"><MetricLabel>Cost basis</MetricLabel></TableHead><TableHead className="numeric"><MetricLabel>Unrealized gain</MetricLabel></TableHead></TableRow></TableHeader><TableBody>{a.holdings.map(h=><TableRow key={h.symbol}><TableCell>{h.symbol}</TableCell><TableCell className="numeric">{h.shares}</TableCell><TableCell className="numeric">{priceDecimal(h.priceMicros)}</TableCell><TableCell className="numeric">{money(h.value)}</TableCell><TableCell className="numeric">{money(h.cost)}</TableCell><TableCell className="numeric">{money(h.gain)}</TableCell></TableRow>)}</TableBody></Table>:<p className="actions-message">You don’t currently hold any stocks. Your total includes cash and any dividends you’ve earned.</p>}</section>
      <details className="product-details"><summary>How your gain adds up</summary><section className="panel portfolio-reconciliation"><div className="panel-heading"><h2><ShieldCheck size={18}/> Gain reconciliation</h2><span className="research-kind">RECONCILED</span></div><div className="portfolio-equation"><span>Realized <strong>{money(a.realized)}</strong></span><b>+</b><span>Unrealized <strong>{money(a.unrealized)}</strong></span><b>+</b><span>Dividends earned <strong>{money(a.income)}</strong></span><b>=</b><span>Total gain <strong>{money(a.gain)}</strong></span></div><p>Trading fees of {money(a.fees)} are already included in cost and realized gain. Dividend payments move value from receivables to cash without earning it twice.</p></section></details>
      {a.dividends.length>0&&<section className="panel"><div className="panel-heading"><h2>Dividends you’ve earned</h2><span className="subtle">Based on the shares you held before the ex-date</span></div><Table><TableHeader><TableRow><TableHead>Symbol</TableHead><TableHead><MetricLabel>Ex-date</MetricLabel></TableHead><TableHead className="numeric">Earned</TableHead><TableHead>Payment recorded</TableHead></TableRow></TableHeader><TableBody>{a.dividends.map(d=><TableRow key={`${d.symbol}:${d.exDate}`}><TableCell>{d.symbol}</TableCell><TableCell>{d.exDate}</TableCell><TableCell className="numeric">{money(d.earned)}</TableCell><TableCell>{d.paidDate??'Unpaid'}</TableCell></TableRow>)}</TableBody></Table></section>}
      <details className="product-details"><summary>Price sources & saved inputs</summary><section className="panel research-provenance"><div className="panel-heading"><h2><Database size={18}/> Frozen research inputs</h2><Button variant="outline" onClick={onOpenData}>Historical data</Button></div><div className="portfolio-inputs">{p.snapshot.bindings.length?p.snapshot.bindings.map(b=><div key={b.dataset.id}><strong>{b.dataset.symbol} · {b.dataset.source}</strong><p>{b.dataset.firstDate} → {b.dataset.lastDate} · {b.dataset.count} observations · {b.dataset.kind==='synthetic'?'Fictional':'Historical'} · USD</p><p>Event source: {b.actions.source} · Revision {b.actions.revision} · {b.actions.events.length} events</p><code>{b.dataset.id}</code></div>):<p>Cash-only ledger; no market-price inputs.</p>}{p.snapshot.benchmark&&<div><strong>Benchmark · {p.snapshot.benchmark.binding.dataset.symbol} · {p.snapshot.benchmark.binding.dataset.source}</strong><p>{p.snapshot.benchmark.binding.dataset.firstDate} → {p.snapshot.benchmark.binding.dataset.lastDate} · {p.snapshot.benchmark.binding.dataset.kind==='synthetic'?'Fictional':'Historical'} · USD</p><p>Event source: {p.snapshot.benchmark.binding.actions.source} · Revision {p.snapshot.benchmark.binding.actions.revision}</p><code>{p.snapshot.benchmark.binding.dataset.id}</code><code>{p.snapshot.benchmark.method}</code></div>}<p>Price observations and the complete event records are saved with this portfolio. Later edits in Historical data do not alter this result. Updating the ledger previews and pins the currently selected records again.</p><code>Portfolio fingerprint: {p.fingerprint}</code></div></section></details>
      <section className="panel"><div className="panel-heading"><h2>Imported transactions</h2><span className="subtle">Latest {Math.min(20,p.snapshot.transactions.length)} of {p.snapshot.transactions.length} · all transactions in download</span></div><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Transaction</TableHead><TableHead>Symbol</TableHead><TableHead className="numeric">Shares</TableHead><TableHead className="numeric"><MetricLabel>Gross amount</MetricLabel></TableHead><TableHead className="numeric">Fee</TableHead></TableRow></TableHeader><TableBody>{p.snapshot.transactions.slice(-20).reverse().map(t=><TableRow key={t.id}><TableCell>{t.date}</TableCell><TableCell>{t.type.replaceAll('_',' ')}<small className="cell-small">{t.reference&&`Ex-date ${t.reference}`}</small></TableCell><TableCell>{t.symbol||'USD'}</TableCell><TableCell className="numeric">{Number(t.units)/1e6||'—'}</TableCell><TableCell className="numeric">{money(t.amount)}</TableCell><TableCell className="numeric">{money(t.fee)}</TableCell></TableRow>)}</TableBody></Table></section>
      <details className="product-details"><summary>Calculation details</summary><p className="portfolio-method">Research conventions: starts in cash; trades execute at the daily closing mark in CSV order, using your recorded gross amount and fees. Splits and dividend entitlements apply before that day’s trades. Fractional split shares are retained exactly. No shorting, borrowing, tax-lot accounting, cash in lieu, spin-offs or other unsupported distributions. Instrument identity and event completeness are declared by you.</p></details>
    </>}
    <Dialog open={open} onOpenChange={value=>{if(!busy){setOpen(value);if(!value)reload();}}}><DialogContent className="import-dialog portfolio-dialog"><DialogHeader><DialogTitle>{p?'Update portfolio':'Import your portfolio'}</DialogTitle><DialogDescription>Upload your complete transaction history. We’ll show a preview before saving. {p?'Saving replaces the current ledger; export it first if you need the old revision.':''}</DialogDescription></DialogHeader>
      <form className="import-form" onSubmit={e=>{e.preventDefault();void submit('preview');}}><fieldset className="import-fields" disabled={busy}>
        <div className="form-grid"><label>Portfolio name<Input value={draft.name} onChange={e=>edit({name:e.target.value})} minLength={2} maxLength={80} required/></label><label>Valuation date<Input type="date" value={draft.asOf} required onInput={e=>edit({asOf:e.currentTarget.value},true)}/></label></div>
        <div className="brokerage-intro"><h3>1 · Upload your transactions</h3><p>Choose the original CSV from Schwab. The file format is detected for you.</p><details><summary>Supported transactions</summary><p>Stock/ETF buys and sells, MoneyLink and bank transfers, and incoming/outgoing wires are supported. Dividends, interest, reinvestments, security transfers, and options need review and stop the import.</p></details><div><a href="/examples/schwab-transactions.csv" download>Download a fictional example</a></div></div>
        <label>Upload transaction CSV<Input type="file" accept=".csv,text/csv" onChange={e=>{void loadFile(e.target.files?.[0]);e.target.value='';}}/></label>
        <div className="portfolio-upload-actions"><Button type="button" variant="outline" onClick={()=>void loadExample()}>Try fictional Schwab file</Button><span className="form-note">Up to 256 KB · 500 transactions · one USD account</span></div>
        <details className="settings-details"><summary>Import settings &amp; original file</summary><div className="settings-fields"><label>CSV format<NativeSelect aria-label="CSV format" value={draft.importFormat??'marketlab-ledger-v1'} onChange={e=>{const broker=e.target.value===SCHWAB_FORMAT;edit({importFormat:broker?SCHWAB_FORMAT:'marketlab-ledger-v1',brokerageOrder:broker?'newest-first':undefined,brokerageKind:broker?'historical':undefined},true);}}><option value={SCHWAB_FORMAT}>Charles Schwab · transaction history</option><option value="marketlab-ledger-v1">MarketLab · normalized ledger</option></NativeSelect></label>
        {isBroker?<><div className="form-grid"><label>Same-day order in this export<NativeSelect aria-label="Same-day order in this export" value={draft.brokerageOrder??'newest-first'} onChange={e=>edit({brokerageOrder:e.target.value as BrokerageOrder},true)}><option value="newest-first">Newest first · reverse same-day rows</option><option value="oldest-first">Oldest first · keep same-day rows</option></NativeSelect></label><label>Transaction source<NativeSelect aria-label="Transaction source" value={draft.brokerageKind??'historical'} onChange={e=>edit({brokerageKind:e.target.value as BrokerageKind},true)}><option value="historical">My historical account export</option><option value="synthetic">Fictional / practice transactions</option></NativeSelect></label></div><p className="brokerage-order-note">Check the file’s ordering: there are no intraday timestamps. The Amount column is net cash; Fees &amp; Comm is kept separately. Dates are modeled at the daily close, without settlement or margin accounting.</p><details className="portfolio-csv-editor"><summary>Inspect or paste the source CSV</summary><Textarea aria-label="Source brokerage CSV" value={draft.csv} onChange={e=>edit({csv:e.target.value},true)} rows={7} maxLength={MAX_CSV_BYTES}/></details></>:<><label>Complete ledger CSV<Textarea aria-label="Complete ledger CSV" value={draft.csv} onChange={e=>edit({csv:e.target.value},true)} rows={7} maxLength={MAX_CSV_BYTES} required/></label><div className="portfolio-csv-help"><code>{LEDGER_HEADER}</code><p>Types: deposit, withdrawal, buy, sell, dividend_payment. Amount is the <strong>gross USD amount</strong>, not the share price; fee is separate. Use unique IDs. Cash flows leave symbol/reference empty. Dividend payments reference their ex-date (YYYY-MM-DD) and must match the earned entitlement.</p><p>Example cash funding row: <code>fund-1,2026-09-14,deposit,,0,1000,0,</code></p><p>Same-date rows execute in file order. Start from cash; opening stock positions and incomplete trade histories are unsupported. Editing a normalized ledger creates a manual import; upload the original brokerage file to create a new conversion receipt.</p></div></>}
        </div></details><Button type="button" variant="outline" onClick={readLedger}>{symbols?'Recheck transactions':'Review transactions'}</Button>
        {brokerageReview&&<><p className="default-summary">Your transactions are ready to review. Match the prices below to continue.</p><details className="product-details"><summary>Transaction import details</summary><BrokerageReceiptView receipt={brokerageReview.receipt} transactions={brokerageReview.transactions}/></details></>}
        {symbols!==null&&<><div className="portfolio-mappings">{symbols.length?symbols.map(symbol=><label key={symbol}>{symbol} price history<NativeSelect value={draft.bindings.find(b=>b.symbol===symbol)?.datasetId??''} required onChange={e=>edit({bindings:draft.bindings.map(b=>b.symbol===symbol?{...b,datasetId:e.target.value}:b)})}><option value="">Select saved unadjusted prices</option>{datasets.filter(d=>d.symbol===symbol&&d.basis==='raw'&&d.priceColumn==='close').map(d=><option key={d.id} value={d.id}>{d.symbol} · {d.firstDate} → {d.lastDate} · {d.kind==='synthetic'?'Fictional':'Historical'}</option>)}</NativeSelect></label>):<p className="form-note">Cash-only ledger: no symbol mapping is needed.</p>}</div>{symbols.some(symbol=>!datasets.some(d=>d.symbol===symbol&&d.basis==='raw'&&d.priceColumn==='close'))&&<div className="brokerage-intro"><p>Some symbols have no saved unadjusted prices yet. Add their prices and company events in Prices & data, then return to this import.</p><Button type="button" variant="outline" onClick={()=>{setOpen(false);onOpenData();}}>Add the missing prices</Button></div>}<p className="form-note">Match each stock with its saved daily prices. Review its splits and dividends in Prices & data before continuing.</p><label>Comparison investment (optional)<NativeSelect aria-label="Cash-flow benchmark" value={draft.benchmarkDatasetId??''} onChange={e=>edit({benchmarkDatasetId:e.target.value})}><option value="">No benchmark comparison</option>{datasets.filter(d=>d.basis==='raw'&&d.priceColumn==='close').map(d=><option key={d.id} value={d.id}>{d.symbol} · {d.firstDate} → {d.lastDate} · {d.kind==='synthetic'?'Fictional':'Historical'}</option>)}</NativeSelect></label><p className="form-note">Use a USD instrument with exact closes for every portfolio valuation date and a complete event record. The benchmark matches external flows, assumes zero trading costs, and holds dividends as unpaid receivables. A withdrawal it cannot fund stops the comparison.</p><label className="actions-confirm"><Checkbox checked={draft.confirmed} onCheckedChange={value=>edit({confirmed:value===true})}/><span>I checked the complete cash-funded history, same-day ordering, and that each dataset matches the same USD instrument.</span></label></>}
      </fieldset>{formError&&<p className="negative import-error" role="alert">{formError}</p>}{preview&&<div className="import-preview"><strong>Reconciled preview · not saved yet</strong><p>Value {money(preview.analysis.value)} · Gain {money(preview.analysis.gain)} · Return {pct(preview.analysis.returnPct)}</p><p>Spendable cash {money(preview.analysis.cash)} · Unpaid dividends {money(preview.analysis.receivables)}</p>{preview.comparison&&<p>Benchmark {preview.comparison.symbol}: {money(preview.comparison.value)} · Your portfolio minus benchmark: {money(preview.comparison.valueDifference)} · Zero benchmark trading costs</p>}<small>{(preview.comparison?.synthetic??preview.analysis.synthetic)?'Contains fictional inputs.':'Historical inputs and mappings are user-supplied.'} Prices and event records will be frozen with this portfolio.</small></div>}{preview&&<ConfidenceCertificate certificate={preview.confidence}/>}<div className="import-actions"><Button type="submit" variant={preview?'outline':'default'} disabled={busy||symbols===null}>{busy?'Checking…':'Preview my portfolio'}</Button>{preview&&<Button type="button" onClick={()=>void submit('save')} disabled={busy}>Save portfolio</Button>}</div></form>
    </DialogContent></Dialog>
    <Dialog open={practiceOpen} onOpenChange={setPracticeOpen}><DialogContent><DialogHeader><DialogTitle>Your first portfolio, ready to explore</DialogTitle><DialogDescription>Fictional transactions and prices. Save this example to try your workspace without uploading anything.</DialogDescription></DialogHeader>{busy&&!preview&&<p role="status">Preparing your practice portfolio…</p>}{preview&&<><div className="practice-summary"><span>Total value<strong>{money(preview.analysis.value)}</strong></span><span>Investment gain<strong>{money(preview.analysis.gain)}</strong></span><span>Trading costs<strong>{money(preview.analysis.fees)}</strong></span></div><p className="form-note">Your $975 in net deposits became {money(preview.analysis.value)} after trading costs.</p><Button onClick={()=>void submit('save')} disabled={busy}>{busy?'Saving…':'Save practice portfolio'}</Button></>}{formError&&<p role="alert" className="negative">{formError}</p>}</DialogContent></Dialog>
  </div>;
}
