'use client';
import { useEffect, useState } from 'react';
import { Plus, Target, Wallet, Bell, ShieldCheck, Download, SlidersHorizontal, CircleHelp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { NativeSelect } from '@/components/ui/native-select';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { toast } from 'sonner';
import ReportDownload from './report-download';
import PlanningBacktest from './planning-backtest';
import { friendlyError } from '@/lib/client-errors';
import { parseDecimal } from '@/lib/finance/core';
import { aggregate, classes, classLabels, emptyValues, feeImpact, goalResult, planScore, project, stress, extraContributions, type Plan, type Account, type Goal, type SavedPlan, type AssetClass, type Projection } from '@/lib/planning/core';
const usd=(v:string)=>{const n=BigInt(v),a=n<0n?-n:n;return `${n<0n?'−':''}$${(a/100n).toLocaleString('en-US')}.${(a%100n).toString().padStart(2,'0')}`;};
const dollars=(v:string)=>{const n=BigInt(v);return `${n/100n}.${(n%100n).toString().padStart(2,'0')}`;};
const today=()=>new Date().toISOString().slice(0,10);
const future=(years:number)=>{const d=new Date();d.setUTCFullYear(d.getUTCFullYear()+years);return d.toISOString().slice(0,10);};
const uid=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,'0')).join('');
function fieldMoney(fd:FormData,key:string){return parseDecimal(String(fd.get(key)||'0')).toString();}
function Stat({label,value,help}:{label:string;value:string;help:string}){return <div className="plan-stat"><span>{label}</span><strong>{value}</strong><small>{help}</small></div>;}
function Curve({points,target}:{points:Projection['points'];target?:string}){
 const max=Math.max(...points.map(p=>Number(p.value)),Number(target??0),1),w=680,h=170,pad=15;
 const path=points.map((p,i)=>`${i?'L':'M'}${pad+i/Math.max(points.length-1,1)*(w-2*pad)},${h-pad-Number(p.value)/max*(h-2*pad)}`).join(' ');
 return <div className="plan-curve"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label={`Hypothetical value rises or falls from ${usd(points[0].value)} to ${usd(points.at(-1)!.value)} over ${points.at(-1)!.month} months. ${target?'Target '+usd(target)+'.':''}`}>
 {target&&<line x1={pad} x2={w-pad} y1={h-pad-Number(target)/max*(h-2*pad)} y2={h-pad-Number(target)/max*(h-2*pad)} stroke="#8b6020" strokeDasharray="6 5"/>}<path d={path} stroke="#16745e" strokeWidth="3" fill="none"/></svg><div><span>Today</span><span>{(points.at(-1)!.month/12).toFixed(1)} years · hypothetical</span></div></div>;
}
export default function Planning({onPortfolio,onBacktests}:{onPortfolio:()=>void;onBacktests:()=>void}){
 const [saved,setSaved]=useState<SavedPlan|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('overview');
 const [account,setAccount]=useState<Account|null>(null),[goal,setGoal]=useState<Goal|null>(null),[formError,setFormError]=useState(''),[allocationOpen,setAllocationOpen]=useState(false),[remove,setRemove]=useState<{kind:'account'|'goal'|'plan';id:string}|null>(null),[scoreOpen,setScoreOpen]=useState(false);
 const [feeYears,setFeeYears]=useState(20),[feeRate,setFeeRate]=useState('0.25'),[feeReturn,setFeeReturn]=useState('5'),[feeMonthly,setFeeMonthly]=useState('200');
 const [scenarioMonthly,setScenarioMonthly]=useState('200'),[scenarioGoal,setScenarioGoal]=useState(''),[historicalStart,setHistoricalStart]=useState(''),[historicalEnd,setHistoricalEnd]=useState('');
 const [shocks,setShocks]=useState<Record<AssetClass,number>>({stocks:-4000,bonds:-1000,cash:0,crypto:-6500,property:-2500,other:-2000});
 async function load(){try{setError('');const r=await fetch('/api/planning',{cache:'no-store'}),d=await r.json() as SavedPlan&{error?:string};if(!r.ok)throw new Error(d.error);setSaved(d);}catch(e){setError(friendlyError(e));}}
 useEffect(()=>{const c=new AbortController();void fetch('/api/planning',{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json() as SavedPlan&{error?:string};if(!r.ok)throw new Error(d.error);if(!c.signal.aborted)setSaved(d);}).catch(e=>{if(!c.signal.aborted)setError(friendlyError(e));});return()=>c.abort();},[]);
 // Re-evaluate alerts against saved balances on return; there is no bank polling.
 useEffect(()=>{const focus=()=>{if(!account&&!goal&&!allocationOpen&&!busy)void load();};window.addEventListener('focus',focus);return()=>window.removeEventListener('focus',focus);},[account,goal,allocationOpen,busy]);
 if(!saved)return <div className="panel plan-panel" role={error?'alert':'status'}>{error||'Opening your plan…'}{error&&<Button onClick={()=>void load()}>Retry</Button>}</div>;
 const p=saved.plan,total=aggregate(p,saved.portfolio),score=planScore(total,p),results=p.goals.map(g=>({goal:g,result:goalResult(g,total)}));
 async function save(next:Plan){if(!saved)return false;setBusy(true);setFormError('');try{const r=await fetch('/api/planning',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:saved.revision,plan:next})}),d=await r.json() as SavedPlan&{error?:string};if(!r.ok)throw new Error(d.error);setSaved({...saved,...d});toast.success('Your plan is saved.');return true;}catch(e){const message=friendlyError(e);setFormError(message);setError(message);return false;}finally{setBusy(false);}}
 function newAccount(){setFormError('');setAccount({id:uid(),name:'',kind:'brokerage',asOf:today(),values:emptyValues(),debt:'0',feesPaid:null,annualFeeBps:null});}
 function newGoal(){setFormError('');setGoal({id:uid(),name:'',kind:'target',target:'1000000',date:future(5),monthly:'20000',accountIds:total.accounts.filter(a=>!['debt','property'].includes(a.kind)).map(a=>a.id),returnBps:500,feeBps:25,inflationBps:250});}
 async function saveAccount(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!account)return;try{const fd=new FormData(e.currentTarget),kind=String(fd.get('kind')) as Account['kind'];const next:Account={...account,name:String(fd.get('name')),kind,asOf:String(fd.get('asOf')),values:Object.fromEntries(classes.map(k=>[k,kind==='debt'?'0':fieldMoney(fd,k)])) as Account['values'],debt:kind==='debt'?fieldMoney(fd,'debt'):'0',feesPaid:String(fd.get('feesPaid')||'')===''?null:fieldMoney(fd,'feesPaid'),annualFeeBps:String(fd.get('annualFee')||'')===''?null:Math.round(Number(fd.get('annualFee'))*100)};if(await save({...p,accounts:[...p.accounts.filter(a=>a.id!==next.id),next]}))setAccount(null);}catch(e){setFormError(friendlyError(e));}}
 async function saveGoal(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!goal)return;try{const fd=new FormData(e.currentTarget),next:Goal={...goal,name:String(fd.get('name')),kind:String(fd.get('kind')) as Goal['kind'],date:String(fd.get('date')),target:fieldMoney(fd,'target'),monthly:fieldMoney(fd,'monthly'),returnBps:Math.round(Number(fd.get('return'))*100),feeBps:Math.round(Number(fd.get('fee'))*100),inflationBps:Math.round(Number(fd.get('inflation'))*100),accountIds:fd.getAll('account').map(String)};if(!next.accountIds.length)throw new Error('Choose at least one account to fund this goal.');if(await save({...p,goals:[...p.goals.filter(g=>g.id!==next.id),next]}))setGoal(null);}catch(e){setFormError(friendlyError(e));}}
 const chosenGoal=results.find(r=>r.goal.id===scenarioGoal)??results[0];
 let impact:ReturnType<typeof feeImpact>|null=null,scenario:Projection|null=null,past:ReturnType<typeof extraContributions>|null=null,calcError='';
 try{impact=feeImpact(total.assets,parseDecimal(feeMonthly).toString(),feeYears*12,Math.round(Number(feeReturn)*100),Math.round(Number(feeRate)*100));if(chosenGoal)scenario=project(chosenGoal.result.initial,(BigInt(chosenGoal.goal.monthly)+parseDecimal(scenarioMonthly)).toString(),chosenGoal.result.months,chosenGoal.goal.returnBps,chosenGoal.goal.feeBps);if(historicalStart&&historicalEnd&&saved.portfolio)past=extraContributions(saved.portfolio.analysis.history,parseDecimal(scenarioMonthly).toString(),historicalStart,historicalEnd);}catch(e){calcError=friendlyError(e);}
 const shock=stress(total,shocks);
 return <div className="planning-space">
 <Tabs value={tab} onValueChange={setTab}><TabsList className="plan-tabs" aria-label="Planning views">{[['overview','Overview'],['goals','Goals'],['accounts','Accounts'],['fees','Cost of fees'],['scenarios','What if?']].map(([id,label])=><TabsTrigger value={id} key={id}>{label}</TabsTrigger>)}</TabsList>
 {error&&<div className="error-banner" role="alert">{error}<Button variant="outline" onClick={()=>void load()}>Reload saved plan</Button></div>}
 <TabsContent value="overview" className="planning-space">
 <section className="plan-hero"><div><span className="plan-kicker">THE WHOLE PICTURE</span><h2>{total.accounts.length?'Your money, with a direction.':'What are you working toward?'}</h2><p>{total.accounts.length?'Bring your balances and goals together. See what a change today could mean later.':'Add a balance, choose a goal, and see your first projection. Your existing portfolio can join the picture.'}</p><Button onClick={total.accounts.length?newGoal:newAccount}>{total.accounts.length?<Target size={18}/>:<Plus size={18}/>} {total.accounts.length?'Set a goal':'Add my first account'}</Button></div><div className="plan-hero-number"><span>Net worth recorded</span><strong>{usd(total.netWorth)}</strong><small>Included assets minus recorded debts</small>{total.oldest&&<small>Balances dated {total.oldest}{total.newest!==total.oldest?' – '+total.newest:''}</small>}</div></section>
 <div className="plan-stats"><Stat label="Assets" value={usd(total.assets)} help="Combined balances you have included"/><Stat label="Debts" value={usd(total.debt)} help="Amounts owed that you have recorded"/><Stat label="Goals" value={String(p.goals.length)} help="Each goal is modeled independently"/><Stat label="Plan readiness" value={score?`${score.value}/100`:'—'} help="A checklist score, not an investment rating"/></div>
 {(total.drift.length>0||total.stale.length>0)&&<section className="plan-alert" aria-label="Portfolio alerts"><Bell size={20}/><div><h2>A quick check-in</h2>{total.drift.map(a=><p key={a.key}>{a.label} is {(Math.abs(a.driftBps!)/100).toFixed(1)} percentage points {a.driftBps!>0?'above':'below'} your target. Current {(a.actualBps/100).toFixed(1)}%; target {(a.targetBps!/100).toFixed(1)}%.</p>)}{total.stale.length>0&&<p>{total.stale.length} account balance{total.stale.length>1?'s are':' is'} more than a month old. Update them before relying on the projections.</p>}<Button variant="outline" onClick={()=>setTab('accounts')}>Review accounts & allocation</Button></div></section>}
 <div className="plan-columns"><section className="panel plan-panel"><div className="plan-section-head"><h2>Your next milestone</h2><Button variant="ghost" onClick={()=>setTab('goals')}>All goals</Button></div>{results[0]?<><span className="plan-eyebrow">{results[0].goal.name}</span><strong className="plan-large">{usd(results[0].result.baseline.ending)}</strong><p>Hypothetical value by {results[0].goal.date}, toward a {usd(results[0].goal.target)} target.</p><Curve points={results[0].result.baseline.points} target={results[0].goal.target}/><span className={'plan-badge '+(results[0].result.onTrack?'':'caution')}>{results[0].result.onTrack?'On track under these assumptions':'Below target under these assumptions'}</span></>:<div className="plan-empty"><Target/><p>A house deposit, a retirement date, or your first savings milestone.</p><Button variant="outline" onClick={total.accounts.length?newGoal:newAccount}>{total.accounts.length?'Create a goal':'Start with an account'}</Button></div>}</section>
 <section className="panel plan-panel"><div className="plan-section-head"><h2>Your plan readiness</h2><ShieldCheck size={20}/></div>{score?<><strong className="plan-large">{score.value}<small> / 100</small></strong><p>Four practical habits. Each completed item adds 25 points.</p><ul className="plan-checklist">{score.items.map(i=><li key={i.label}><span>{i.met?'Complete':'To do'}</span>{i.label}</li>)}</ul><Button variant="outline" onClick={()=>setScoreOpen(true)}>Share my checklist score</Button></>:<p>Add an account to see your checklist. This measures how complete your plan is, not the quality of your investments.</p>}</section></div>
 <section className="panel plan-panel"><h2>Understand your numbers</h2><div className="plan-learning"><div><h3>Net worth</h3><p>Your recorded assets ({usd(total.assets)}) minus your recorded debts ({usd(total.debt)}). Missing accounts change the picture.</p></div><div><h3>Allocation drift</h3><p>The gap between what you own and your chosen mix. A 65% stock weight against a 60% target is a 5 percentage-point gap.</p></div><div><h3>The cost of a fee</h3><p>Money paid in fees also stops earning returns. Your cost report shows both the payments and the potential effect on growth.</p><Button variant="link" onClick={()=>setTab('fees')}>See my cost report</Button></div></div></section>
 </TabsContent>
 <TabsContent value="accounts" className="planning-space">
 <div className="plan-section-head"><div><h2>Your accounts</h2><p>Manual balances and your imported portfolio, in USD. Add each account once.</p></div><Button onClick={newAccount}><Plus/>Add account</Button></div>
 {saved.portfolio&&<section className="panel plan-panel">{saved.portfolio.analysis.synthetic?<p><strong>Your practice portfolio is fictional.</strong> It stays out of real net worth. Import your own history when you’re ready.</p>:<><label className="plan-check"><Checkbox checked={p.includePortfolio} disabled={busy} onCheckedChange={v=>void save({...p,includePortfolio:v===true})}/>Include {saved.portfolio.name} · {usd(saved.portfolio.analysis.value)}</label><label className="plan-inline-label">Classify its invested holdings<NativeSelect value={p.portfolioClass} onChange={e=>void save({...p,portfolioClass:e.target.value as AssetClass})} disabled={busy}>{classes.filter(k=>k!=='cash').map(k=><option key={k} value={k}>{classLabels[k]}</option>)}</NativeSelect></label><p>Cash is classified separately. Use “Other assets” for a mixed portfolio you cannot classify as one group.</p></>}<Button variant="outline" onClick={onPortfolio}>Open imported portfolio</Button></section>}
 {p.accounts.length===0?<section className="panel plan-panel"><Wallet/><h3>Add the balances you want to track</h3><p>A brokerage, retirement plan, bank balance, property, crypto account, or debt. Bank syncing is not connected; update these balances yourself.</p></section>:<div className="plan-account-grid">{p.accounts.map(a=><section className="panel plan-panel" key={a.id}><span className="plan-eyebrow">{a.kind==='retirement'?'Retirement / 401(k)':a.kind}</span><h3>{a.name}</h3><strong className="plan-large">{a.kind==='debt'?'-':''}{usd(a.kind==='debt'?a.debt:classes.reduce((s,k)=>s+BigInt(a.values[k]),0n).toString())}</strong><p>Updated balance: {a.asOf}</p><div className="plan-actions"><Button variant="outline" onClick={()=>{setFormError('');setAccount(a);}}>Update</Button><Button variant="ghost" onClick={()=>setRemove({kind:'account',id:a.id})}>Remove</Button></div></section>)}</div>}
 <section className="panel plan-panel"><div className="plan-section-head"><div><h2>Allocation & alerts</h2><p>How your included assets are divided. Debts are excluded from these percentages.</p></div><Button variant="outline" onClick={()=>{setFormError('');setAllocationOpen(true);}}><SlidersHorizontal/>Set targets</Button></div>
 <Table><TableHeader><TableRow><TableHead>Asset group</TableHead><TableHead>Value</TableHead><TableHead>Current</TableHead><TableHead>Your target</TableHead><TableHead>Gap</TableHead></TableRow></TableHeader><TableBody>{total.allocation.map(a=><TableRow key={a.key}><TableCell>{a.label}</TableCell><TableCell>{usd(a.value)}</TableCell><TableCell>{(a.actualBps/100).toFixed(1)}%</TableCell><TableCell>{a.targetBps===null?'Not set':`${a.targetBps/100}%`}</TableCell><TableCell>{a.driftBps===null?'—':`${a.driftBps>0?'+':''}${(a.driftBps/100).toFixed(1)} pp`}</TableCell></TableRow>)}</TableBody></Table><p>“pp” means percentage points. Alerts appear here when the gap reaches your {p.thresholdBps/100}-point threshold. They update when you save balances or return to the app. Rebalancing can create taxes or trading costs.</p></section>
 </TabsContent>
 <TabsContent value="goals" className="planning-space">
 <div className="plan-section-head"><div><h2>Give your money a purpose</h2><p>Targets are in future dollars. The projections use the assumptions you choose.</p></div><Button onClick={total.accounts.length?newGoal:newAccount}><Plus/>{total.accounts.length?'Add goal':'Add an account first'}</Button></div>
 {!results.length&&<section className="panel plan-panel plan-empty"><Target/><h3>What do you want to reach?</h3><p>Pick a target amount and a date. We’ll show what your balance and monthly contributions could become.</p></section>}
 {results.map(({goal:g,result:r})=><section className="panel plan-panel" key={g.id}><div className="plan-section-head"><div><span className="plan-eyebrow">{g.kind}</span><h2>{g.name}</h2></div><Button variant="outline" onClick={()=>{setFormError('');setGoal(g);}}>Edit goal</Button></div><div className="plan-stats"><Stat label="Saved toward this goal" value={usd(r.initial)} help={`${r.progress.toFixed(1)}% of the target today`}/><Stat label="Your target" value={usd(g.target)} help={`By ${g.date}`}/><Stat label="Hypothetical ending value" value={usd(r.baseline.ending)} help={`${g.returnBps/100}% nominal return; ${g.feeBps/100}% annual fee`}/><Stat label="Monthly contribution" value={usd(g.monthly)} help="Added at the end of each modeled month"/></div><Curve points={r.baseline.points} target={g.target}/><div className="plan-insight"><strong>{r.onTrack?'On track under your assumptions':`${usd(r.gap)} below your target under these assumptions`}</strong><p>{r.onTrack?'Actual returns can be lower. Compare the lower-return scenario before making a decision.':r.neededMonthly?`${usd(r.neededMonthly)} a month would reach this target under the same assumptions. You can also change the date or target.`:'There is no remaining full contribution month in this projection. Review the target date.'}</p></div><details className="product-details"><summary>Compare assumptions & understand this projection</summary><div className="plan-panel"><p>With a {Math.max(-2000,g.returnBps-300)/100}% assumed return: <strong>{usd(r.low.ending)}</strong>. With a {Math.min(2000,g.returnBps+300)/100}% assumed return: <strong>{usd(r.high.ending)}</strong>. These are examples, not a probability range.</p><p>The central result is about {usd(r.todaysDollars)} in today’s purchasing power at {g.inflationBps/100}% assumed inflation. Your target stays in future dollars. Taxes and changes in contribution amounts are excluded.</p><p>Each month applies one twelfth of the nominal annual return, then one twelfth of the annual fee, then your contribution. Every step rounds to cents. The date includes {r.months} complete months.</p><p>A retirement target is a savings milestone, not an estimate of how long retirement income will last.</p><Button variant="ghost" onClick={()=>setRemove({kind:'goal',id:g.id})}>Delete this goal</Button></div></details></section>)}
 <p className="plan-note">Goals are calculated independently. When two goals use the same account, that money is counted in each projection; it cannot fund both targets at the same time.</p>
 </TabsContent>
 <TabsContent value="fees" className="planning-space">
 <section className="plan-hero"><div><span className="plan-kicker">MAKE HIDDEN COSTS VISIBLE</span><h2>Small percentages. A lasting difference.</h2><p>See the fees in your records, then explore what ongoing costs could mean over time.</p></div><div className="plan-hero-number"><span>Recorded fees paid to date</span><strong>{usd(total.feesPaid)}</strong><small>{total.unknownFees?`${total.unknownFees} asset accounts have no fee total recorded.`:'Based on the fee totals you supplied.'}</small><small>Only recorded periods; fund expenses and unreported fees may be missing.</small></div></section>
 <section className="panel plan-panel"><h2>Your long-term cost report</h2><div className="plan-fields"><label>Years to retirement or target<Input type="number" min="1" max="60" value={feeYears} onChange={e=>setFeeYears(Math.max(1,Math.min(60,Number(e.target.value)||1)))}/></label><label>Monthly contribution ($)<Input type="number" min="0" max="999999999" step="0.01" value={feeMonthly} onChange={e=>setFeeMonthly(e.target.value)}/></label><label>Assumed annual return (%)<Input type="number" min="-20" max="20" step="0.1" value={feeReturn} onChange={e=>setFeeReturn(e.target.value)}/></label><label>Assumed total annual fee (%)<Input type="number" min="0" max="5" step="0.01" value={feeRate} onChange={e=>setFeeRate(e.target.value)}/></label></div><p>Starts with your included assets, {usd(total.assets)}. The 0.25% starting fee is an editable illustration, not a measurement of your accounts. Include fund expenses and advisory fees in your chosen assumption.</p>{calcError&&<p role="alert">{calcError}</p>}{impact&&<><div className="plan-stats"><Stat label="Potential reduction in ending value" value={usd(impact.drag)} help="Compared with the same return and no ongoing fee"/><Stat label="Projected fees charged" value={usd(impact.net.fees)} help="Hypothetical payments over the selected years"/><Stat label="Effect on potential growth" value={usd(impact.lostGrowth)} help="Additional difference caused by compounding"/></div><Curve points={impact.net.points}/><div className="plan-insight"><strong>With fees: {usd(impact.net.ending)} · Without fees: {usd(impact.gross.ending)}</strong><p>Future fees and their growth effect are included in the difference above. Historical fees are already reflected in today’s balance and are not charged again.</p></div><details className="product-details"><summary>Account fee assumptions</summary><div className="plan-panel">{total.accounts.filter(a=>a.kind!=='debt').map(a=><p key={a.id}>{a.name}: recorded fees {a.feesPaid===null?'unknown':usd(a.feesPaid)}; annual rate {a.annualFeeBps===null?'unknown':`${a.annualFeeBps/100}%`}.</p>)}<p>This report uses the single annual fee assumption above. It does not infer fees from returns or claim full lifetime coverage. Property, cash and debt may need separate treatment; adjust which accounts are included before using the scenario.</p><a href="https://www.investor.gov/introduction-investing/getting-started/understanding-fees" target="_blank" rel="noreferrer">Learn about investment fees at Investor.gov</a></div></details></>}</section>
 </TabsContent>
 <TabsContent value="scenarios" className="planning-space">
 <section className="panel plan-panel"><div className="plan-section-head"><div><h2>What if I saved more each month?</h2><p>Change one habit and compare it with a saved goal.</p></div><CircleHelp/></div><div className="plan-fields"><label>Goal<NativeSelect value={chosenGoal?.goal.id??''} onChange={e=>setScenarioGoal(e.target.value)}><option value="" disabled>Choose a saved goal</option>{results.map(r=><option key={r.goal.id} value={r.goal.id}>{r.goal.name}</option>)}</NativeSelect></label><label>Extra contribution each month ($)<Input type="number" min="0" max="999999999" step="0.01" value={scenarioMonthly} onChange={e=>setScenarioMonthly(e.target.value)}/></label></div>{chosenGoal&&scenario?<><div className="plan-stats"><Stat label="Current plan" value={usd(chosenGoal.result.baseline.ending)} help={`At ${usd(chosenGoal.goal.monthly)} per month`}/><Stat label="With the extra contribution" value={usd(scenario.ending)} help="Same date, return and fee assumptions"/><Stat label="Difference at the target date" value={usd((BigInt(scenario.ending)-BigInt(chosenGoal.result.baseline.ending)).toString())} help="Includes extra deposits and hypothetical growth"/></div><Curve points={scenario.points} target={chosenGoal.goal.target}/></>:<p>Create a goal to see a personalized contribution scenario.</p>}{calcError&&<p role="alert">{calcError}</p>}</section>
 <PlanningBacktest goal={chosenGoal?.goal} initial={chosenGoal?.result.initial} months={chosenGoal?.result.months} onBacktests={onBacktests}/><section className="panel plan-panel"><h2>What if a severe market shock happened today?</h2><p>An illustrative stress test, not a replay of 2008 or a forecast. Change the assumed shock for each asset group.</p><div className="plan-fields">{classes.map(k=><label key={k}>{classLabels[k]} change (%)<Input type="number" min="-100" max="100" step="1" value={shocks[k]/100} onChange={e=>setShocks(v=>({...v,[k]:Math.max(-10000,Math.min(10000,Math.round((Number(e.target.value)||0)*100)))}))}/></label>)}</div><div className="plan-stats"><Stat label="Assets after shock" value={usd(shock.after)} help="Applies each change to your recorded allocation"/><Stat label="Change in assets" value={usd(shock.change)} help="Immediate hypothetical change, before tax or trades"/><Stat label="Net worth after shock" value={usd(shock.netWorth)} help="Your recorded debt stays unchanged"/></div><p>Assumes all shocks occur together. It models neither recovery time nor the likelihood of this event. Mixed holdings classified as “Other assets” use that group’s shock.</p></section>
 <section className="panel plan-panel"><h2>What if I had contributed more in the past?</h2><p>Use the percentage changes from your imported portfolio to model the extra monthly contribution above.</p>{saved.portfolio?<><div className="plan-fields"><label>Start date<Input type="date" min={saved.portfolio.analysis.history[0]?.date} max={saved.portfolio.asOf} value={historicalStart} onChange={e=>setHistoricalStart(e.target.value)}/></label><label>End date<Input type="date" min={saved.portfolio.analysis.history[0]?.date} max={saved.portfolio.asOf} value={historicalEnd} onChange={e=>setHistoricalEnd(e.target.value)}/></label></div><p>Available: {saved.portfolio.analysis.history[0]?.date} to {saved.portfolio.asOf}.{saved.portfolio.analysis.synthetic?' This history is fictional practice data.':''}</p>{past&&<div className="plan-stats"><Stat label="Extra amount deposited" value={usd(past.contributed)} help="At the first observed close in each selected month"/><Stat label="Hypothetical ending value" value={usd(past.value)} help="Follows the imported portfolio’s return pattern"/><Stat label="Growth on those deposits" value={usd(past.gain)} help="Ending value minus the extra deposits"/></div>}<p>This uses your existing portfolio calculation’s return history. It assumes the same exposure, includes costs already reflected in those returns, and excludes any additional trading costs, taxes or execution constraints. It is not an executable trade simulation.</p></>:<Button variant="outline" onClick={onPortfolio}>Import a portfolio to compare history</Button>}</section>
 </TabsContent></Tabs>
 <footer className="plan-footer"><span>Planning illustrations, not investment advice or guaranteed outcomes.</span><Button variant="outline" asChild><ReportDownload href="/api/planning?download=1" download><Download/>Download my plan</ReportDownload></Button><a href="/trust">Privacy & methodology</a><a href="/status">Service status</a><a href="/support">Support</a></footer>
 <Dialog open={!!account} onOpenChange={v=>{if(!v&&!busy)setAccount(null);}}><DialogContent className="plan-dialog"><DialogHeader><DialogTitle>{p.accounts.some(a=>a.id===account?.id)?'Update account':'Add an account'}</DialogTitle><DialogDescription>Enter a recent USD balance. Do not add an account that is already included through your imported portfolio.</DialogDescription></DialogHeader>{account&&<form onSubmit={e=>void saveAccount(e)} className="plan-form"><fieldset disabled={busy}><div className="plan-fields"><label>Account nickname<Input name="name" defaultValue={account.name} minLength={2} maxLength={80} required placeholder="e.g. Retirement plan"/></label><label>Account type<NativeSelect name="kind" value={account.kind} onChange={e=>setAccount({...account,kind:e.target.value as Account['kind']})}>{['brokerage','retirement','bank','crypto','property','debt','other'].map(k=><option key={k} value={k}>{k==='retirement'?'Retirement / 401(k)':k[0].toUpperCase()+k.slice(1)}</option>)}</NativeSelect></label><label>Balance date<Input type="date" name="asOf" defaultValue={account.asOf} max={today()} required/></label></div>{account.kind==='debt'?<label>Amount owed ($)<Input type="number" name="debt" defaultValue={dollars(account.debt)} min="0" max="999999999" step="0.01" required/></label>:<><p>Split this account’s balance into the groups you know. Put unclassified holdings in “Other assets.”</p><div className="plan-fields">{classes.map(k=><label key={k}>{classLabels[k]} ($)<Input name={k} type="number" min="0" max="999999999" step="0.01" defaultValue={dollars(account.values[k])}/></label>)}</div><details className="product-details"><summary>Fees, if you know them</summary><div className="plan-fields"><label>Fees paid in your records ($)<Input name="feesPaid" type="number" min="0" max="999999999" step="0.01" defaultValue={account.feesPaid===null?'':dollars(account.feesPaid)} placeholder="Unknown"/></label><label>Annual total fee (%)<Input name="annualFee" type="number" min="0" max="5" step="0.01" defaultValue={account.annualFeeBps===null?'':account.annualFeeBps/100} placeholder="Unknown"/></label></div><p>Leave unknown values blank. Zero means you checked and recorded no fees.</p></details></>}{formError&&<p className="error-banner" role="alert">{formError}</p>}<Button type="submit">{busy?'Saving…':'Save account'}</Button></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!goal} onOpenChange={v=>{if(!v&&!busy)setGoal(null);}}><DialogContent className="plan-dialog"><DialogHeader><DialogTitle>{p.goals.some(g=>g.id===goal?.id)?'Edit goal':'Set a goal'}</DialogTitle><DialogDescription>Use a target amount and date that matter to you. You can change every assumption.</DialogDescription></DialogHeader>{goal&&<form onSubmit={e=>void saveGoal(e)} className="plan-form"><fieldset disabled={busy}><div className="plan-fields"><label>Goal name<Input name="name" defaultValue={goal.name} minLength={2} maxLength={80} required placeholder="e.g. My first home"/></label><label>Goal type<NativeSelect name="kind" defaultValue={goal.kind}><option value="target">Target amount</option><option value="home">House down payment</option><option value="retirement">Retirement savings</option></NativeSelect></label><label>Target amount, future dollars ($)<Input type="number" name="target" min="1" max="999999999" step="0.01" defaultValue={dollars(goal.target)} required/></label><label>Target date<Input type="date" name="date" min={today()} max={future(60)} defaultValue={goal.date} required/></label><label>Monthly contribution ($)<Input type="number" name="monthly" min="0" max="999999999" step="0.01" defaultValue={dollars(goal.monthly)} required/></label></div><fieldset className="plan-account-choices"><legend>Accounts for this goal</legend>{total.accounts.filter(a=>a.kind!=='debt').map(a=><label className="plan-check" key={a.id}><Checkbox name="account" value={a.id} defaultChecked={goal.accountIds.includes(a.id)}/>{a.name}</label>)}</fieldset><details className="product-details"><summary>Projection assumptions · {goal.returnBps/100}% return, {goal.feeBps/100}% fee</summary><div className="plan-fields"><label>Nominal annual return (%)<Input name="return" type="number" min="-20" max="20" step="0.01" defaultValue={goal.returnBps/100} required/></label><label>Total annual fee (%)<Input name="fee" type="number" min="0" max="5" step="0.01" defaultValue={goal.feeBps/100} required/></label><label>Annual inflation (%)<Input name="inflation" type="number" min="0" max="15" step="0.01" defaultValue={goal.inflationBps/100} required/></label></div><p>Starting assumptions are illustrations, not expected returns for your investments. Past backtest returns are not used as a forecast.</p></details>{formError&&<p className="error-banner" role="alert">{formError}</p>}<Button type="submit">{busy?'Saving…':'Save goal'}</Button></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={allocationOpen} onOpenChange={v=>{if(!busy)setAllocationOpen(v);}}><DialogContent className="plan-dialog"><DialogHeader><DialogTitle>Your target allocation</DialogTitle><DialogDescription>Choose your own mix, totaling 100%. Enter the percentages you want. A target is your choice, not a MarketLab recommendation.</DialogDescription></DialogHeader><form className="plan-form" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);void save({...p,target:Object.fromEntries(classes.map(k=>[k,Math.round(Number(fd.get(k))*100)])) as NonNullable<Plan['target']>,thresholdBps:Math.round(Number(fd.get('threshold'))*100),alertsEnabled:fd.get('alerts')==='on'}).then(ok=>{if(ok)setAllocationOpen(false);});}}><fieldset disabled={busy}><div className="plan-fields">{classes.map(k=><label key={k}>{classLabels[k]} (%)<Input name={k} type="number" min="0" max="100" step="0.01" defaultValue={(p.target?.[k]??0)/100} required/></label>)}<label>Alert when a gap reaches (percentage points)<Input name="threshold" type="number" min="1" max="25" step="0.1" defaultValue={p.thresholdBps/100} required/></label></div><label className="plan-check"><Checkbox name="alerts" defaultChecked={p.alertsEnabled}/>Show allocation alerts in MarketLab</label><p>Alerts use saved balances. They do not send emails, monitor connected banks, or place trades.</p>{formError&&<p className="error-banner" role="alert">{formError}</p>}<Button type="submit">Save targets</Button></fieldset></form></DialogContent></Dialog>
 <Dialog open={!!remove} onOpenChange={v=>{if(!v&&!busy)setRemove(null);}}><DialogContent><DialogHeader><DialogTitle>Remove this {remove?.kind}?</DialogTitle><DialogDescription>{remove?.kind==='account'?'This removes the saved balance and unlinks it from your goals. It does not close the real financial account.':'This deletes the saved goal. Your accounts stay in your workspace.'}</DialogDescription></DialogHeader><div className="plan-actions"><Button variant="outline" onClick={()=>setRemove(null)}>Keep it</Button><Button disabled={busy} onClick={()=>{if(remove)void save(remove.kind==='account'?{...p,accounts:p.accounts.filter(a=>a.id!==remove.id),goals:p.goals.map(g=>({...g,accountIds:g.accountIds.filter(i=>i!==remove.id)}))}:{...p,goals:p.goals.filter(g=>g.id!==remove.id)}).then(ok=>{if(ok)setRemove(null);});}}>Remove</Button></div></DialogContent></Dialog>
 <Dialog open={scoreOpen} onOpenChange={setScoreOpen}><DialogContent><DialogHeader><DialogTitle>Share your plan readiness</DialogTitle><DialogDescription>Review this text before copying. It includes no balances, account names or goal amounts.</DialogDescription></DialogHeader><p>My MarketLab plan readiness is {score?.value}/100. It tracks four planning habits—not investment performance or financial health. Explore MarketLab: {typeof window!=='undefined'?window.location.origin:''}</p><Button onClick={()=>{void (navigator.clipboard? navigator.clipboard.writeText(`My MarketLab plan readiness is ${score?.value}/100. It tracks four planning habits—not investment performance or financial health. Explore MarketLab: ${window.location.origin}`):Promise.reject(new Error('Copy unavailable'))).then(()=>toast.success('Copied. Share it wherever you choose.')).catch(()=>toast.error('Copy the text above to share it.'));}}>Copy reviewed text</Button></DialogContent></Dialog>
 </div>;
}
