'use client';
import { friendlyError } from '@/lib/client-errors';
import MetricLabel from './metric-label';
import { defaultResearchDates } from '@/lib/research-defaults';
import type { StrategyTemplate } from '@/lib/planning/community';
import ReportDownload from './report-download';
import { useEffect, useState } from 'react';
import { FlaskConical, Plus, Download, Database, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { NativeSelect } from '@/components/ui/native-select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { toast } from 'sonner';
import { RESEARCH_ASSUMPTIONS, type ResearchDraft, type ResearchAnalysis, type SavedResearch, type RunSummary } from '@/lib/finance/research';
import type { DatasetSummary, SavedDataset } from '@/lib/finance/market-data';
import ConfidenceCertificate from './confidence-certificate';
import { researchCertificate, type ConfidenceCertificate as Certificate } from '@/lib/finance/confidence';
import BackgroundResearch from './background-research';
import ResearchReplay from './research-replay';
import ResearchComparison from './research-comparison';
import EquityChart from './equity-chart';
import ResearchShareDialog from './research-share-dialog';
import ResearchDiscussionDialog from './research-discussion-dialog';
const money=(s:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(s)/100);
const pct=(n:number)=>(n>0?'+':'')+n.toFixed(2)+'%';
const metric=(n:number|null,suffix='')=>n===null?'N/A':n.toFixed(3)+suffix;
function shareLabel(value:string){const [n,d='1']=value.split('/').map(BigInt);if(1000000n%BigInt(d)!==0n)return value;const units=n*1000000n/BigInt(d);return `${units/1000000n}.${(units%1000000n).toString().padStart(6,'0')}`.replace(/\.?0+$/,'');}
async function read<T>(res:Response):Promise<T>{const d=await res.json() as {error?:string};if(!res.ok)throw new Error(d.error||'Research request failed.');return d as T;}
const fresh=():ResearchDraft=>({name:'Trend strategy',assetId:'',benchmarkId:'',start:'',end:'',holdoutStart:'',window:20,initialCash:'10000',feeBps:10,slippageBps:5,confirmed:false});
const series=[{key:'strategy',name:'Trend strategy',color:'#20775b'},{key:'buyHold',name:'Buy and hold',color:'#bd9245'},{key:'benchmark',name:'Benchmark',color:'#657fb5'}] as const;
export default function ResearchLab({onOpenData,template}:{onOpenData:()=>void;template?:StrategyTemplate|null}) {
  const [runs,setRuns]=useState<RunSummary[]>([]),[datasets,setDatasets]=useState<DatasetSummary[]>([]),[selected,setSelected]=useState(''),[run,setRun]=useState<SavedResearch|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
  const [open,setOpen]=useState(false),[draft,setDraft]=useState<ResearchDraft>(fresh),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[preview,setPreview]=useState<{analysis:ResearchAnalysis;fingerprint:string;confidence:Certificate}|null>(null),[period,setPeriod]=useState<'full'|'development'|'holdout'>('full');
  const [autoDates,setAutoDates]=useState(true),[dateBusy,setDateBusy]=useState(false);
  useEffect(()=>{if(!open||!autoDates||!draft.assetId)return;const c=new AbortController();void fetch(`/api/datasets?id=${draft.assetId}`,{cache:'no-store',signal:c.signal}).then(read<SavedDataset>).then(data=>{const dates=defaultResearchDates(data.observations,draft.window);if(!c.signal.aborted)setDraft(d=>({...d,...dates,confirmed:false}));}).catch(e=>{if(!c.signal.aborted)setFormError(friendlyError(e));}).finally(()=>{if(!c.signal.aborted)setDateBusy(false);});return()=>c.abort();},[open,autoDates,draft.assetId,draft.window]);
  useEffect(()=>{const c=new AbortController();void Promise.all([fetch('/api/research',{cache:'no-store',signal:c.signal}).then(read<{runs:RunSummary[]}>),fetch('/api/datasets',{cache:'no-store',signal:c.signal}).then(read<{datasets:DatasetSummary[]}>)]).then(([r,d])=>{if(!c.signal.aborted){setRuns(r.runs);setDatasets(d.datasets);setSelected(s=>s||r.runs[0]?.id||'');}}).catch(e=>{if(!c.signal.aborted)setError(friendlyError(e));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[refresh]);
  useEffect(()=>{if(!selected)return;const c=new AbortController();void fetch(`/api/research?id=${selected}`,{cache:'no-store',signal:c.signal}).then(read<{run:SavedResearch}>).then(d=>{if(!c.signal.aborted)setRun(d.run);}).catch(e=>{if(!c.signal.aborted)setError(friendlyError(e));});return()=>c.abort();},[selected,refresh]);
  function reload(){setLoading(true);setError('');setRefresh(n=>n+1);}
  function start(){const usable=datasets.filter(d=>d.basis==='raw'&&d.priceColumn==='close'&&d.count>=8);const first=usable.find(d=>d.count>=26)??usable[0];setAutoDates(!!template||!run);setDateBusy((!!template||!run)&&!!first);setDraft(template?{...fresh(),name:template.title,window:template.window,feeBps:template.feeBps,slippageBps:template.slippageBps,assetId:first?.id??'',benchmarkId:first?.id??''}:run?{...run.snapshot.config,name:run.name+' copy',confirmed:false}:{...fresh(),window:first?Math.min(20,first.count-6):20,assetId:first?.id??'',benchmarkId:first?.id??'',name:first?`${first.symbol} trend strategy`:'Trend strategy'});setPreview(null);setFormError('');setOpen(true);}
  function edit(patch:Partial<ResearchDraft>){setDraft(d=>({...d,...patch,confirmed:patch.confirmed??false}));setPreview(null);setFormError('');}
  async function submit(mode:'preview'|'save'){setBusy(true);setFormError('');try{const res=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,draft,fingerprint:preview?.fingerprint})});if(mode==='preview')setPreview(await read<{analysis:ResearchAnalysis;fingerprint:string;confidence:Certificate}>(res));else{const result=await read<{run:SavedResearch;message:string}>(res);setRun(result.run);setSelected(result.run.id);setPeriod('full');setRuns(r=>[result.run,...r.filter(v=>v.id!==result.run.id)]);setOpen(false);toast.success('Backtest saved. Ready to view or share.');}}catch(e){setFormError(friendlyError(e));}finally{setBusy(false);}}
  const active=run?.id===selected?run:null,part=active?.analysis[period],hasUsablePrices=datasets.some(d=>d.basis==='raw'&&d.priceColumn==='close'&&d.count>=8);
  return <div className="research-workspace">
    {template&&<section className="panel plan-panel"><h2>{template.title}</h2><p>This template follows a {template.window}-price trend window. Applying it uses your own saved prices, dates and fresh calculation; the publisher’s result does not transfer to your report.</p><Button onClick={hasUsablePrices?start:onOpenData} disabled={loading}>{hasUsablePrices?'Apply to my prices':'Add my price history'}</Button></section>}
    {runs.length>0&&<div className="portfolio-toolbar"><div><h2>Your saved backtests</h2><p>Test a simple trend strategy against buying and holding.</p></div><Button variant={runs.length?'outline':'default'} onClick={hasUsablePrices?start:onOpenData} disabled={loading}><Plus size={16}/> {hasUsablePrices?'New backtest':'Add price history'}</Button></div>}
    {error&&<div className="error-banner" role="alert">{error}<button onClick={reload}>Retry</button></div>}
    {loading?<div className="panel empty-state" role="status">Loading your backtests…</div>:<>
      {runs.length>0&&<div className="research-picker"><label htmlFor="research-run">Saved backtest</label><NativeSelect id="research-run" value={selected} onChange={e=>{setSelected(e.target.value);setError('');setPeriod('full');}}>{runs.map(r=><option key={r.id} value={r.id}>{r.name} · {r.symbol} / {r.benchmark}</option>)}</NativeSelect><span>{runs.length} / 30 saved</span></div>}
      {!runs.length&&!error&&<section className="panel research-empty"><FlaskConical size={36}/><h2>What if you had followed a simple rule?</h2><p>Choose a stock and we’ll fill in the dates, starting amount, and trading costs. You can adjust them whenever you like.</p><div><Button onClick={hasUsablePrices?start:onOpenData}>{hasUsablePrices?'Create my first backtest':'Add price history'}</Button></div><p className="research-muted">A backtest shows what would have happened in the past. It doesn’t predict future returns.</p></section>}
      {selected&&!active&&!error&&<div className="panel empty-state" role="status">Opening your report…</div>}
      {active&&part&&<>
        <div className="portfolio-toolbar"><div><h2>{active.name}</h2><p>{active.symbol} · Trend strategy · {active.start} to {active.end}</p></div><div><ResearchShareDialog key={`share-${active.id}`} id={active.id}/><ResearchDiscussionDialog key={`discussion-${active.id}`} id={active.id}/><details className="export-menu"><summary>Download report</summary><Button variant="outline" asChild><ReportDownload href={`/api/research?id=${active.id}&download=json`} download><Download size={16}/> Full report JSON</ReportDownload></Button><Button variant="outline" asChild><ReportDownload href={`/api/research?id=${active.id}&download=csv`} download>Spreadsheet (CSV)</ReportDownload></Button></details></div></div>
        <div className="research-periods" aria-label="Evaluation period">{([{key:'full',label:'Full period'},{key:'development',label:'Earlier period'},{key:'holdout',label:'Later period'}] as const).map(p=><Button key={p.key} variant={period===p.key?'default':'outline'} aria-pressed={period===p.key} onClick={()=>setPeriod(p.key)}>{p.label}</Button>)}</div>
        <ConfidenceCertificate certificate={researchCertificate(active,period)}/><details className="product-details"><summary>Check this calculation</summary><ResearchReplay key={active.id} id={active.id} receipt={active.replayReceipt} onVerified={()=>setRefresh(n=>n+1)}/><details className="product-details"><summary>Additional calculation details</summary><BackgroundResearch key={active.id} id={active.id}/></details></details>
        <div className="portfolio-metrics"><div><span>Investment return</span><strong className={part.strategy.returnPct>=0?'positive':'negative'}>{pct(part.strategy.returnPct)}</strong><small>Growth after the modeled trading costs</small></div><div><MetricLabel>Benchmark</MetricLabel><strong>{pct(part.benchmark.returnPct)}</strong><small>{active.benchmark} · modeled buy-and-hold</small></div><div><span>Difference in returns</span><strong>{part.outperformancePct.toFixed(2)} pp</strong><small>Strategy minus comparison, in percentage points</small></div><div><MetricLabel>Drawdown</MetricLabel><strong>{pct(part.strategy.maxDrawdown)}</strong><small>Largest drop from an earlier high</small></div><div><span>Strategy ending value</span><strong>{money(part.strategy.history.at(-1)!.value)}</strong><small>Initial cash ${Number(active.snapshot.config.initialCash).toLocaleString('en-US')}</small></div><div><span>Executed trades</span><strong>{part.strategy.trades.length}</strong><small>{money(part.strategy.fees)} in total trading fees</small></div></div>
        <section className="panel"><div className="panel-heading"><div><h2>How your investment would have changed</h2><p>{part.start} → {part.end} · {part.observations} observations</p></div><span className="research-kind">{active.analysis.synthetic?'FICTIONAL EXAMPLE':'HYPOTHETICAL RESULT'}</span></div><EquityChart key={period} part={part} initial={active.snapshot.config.initialCash} events={active.snapshot.asset.actions.events}/><div className="research-chart-note">Compare the strategy with simply buying and holding. Each period starts with the same amount of cash.</div></section>
        <details className="product-details"><summary>More performance measures</summary><section className="panel"><div className="panel-heading"><div><h2>Return & risk comparison</h2><p>{part.strategyRisk.intervals} matched intervals · longest gap {part.longestGapDays} calendar days</p></div></div><Table><TableHeader><TableRow><TableHead>Measure</TableHead>{series.map(s=><TableHead className="numeric" key={s.key}>{s.name}</TableHead>)}</TableRow></TableHeader><TableBody>
          <TableRow><TableCell><MetricLabel>Return after costs</MetricLabel></TableCell>{series.map(s=><TableCell key={s.key} className="numeric">{pct(part[s.key].returnPct)}</TableCell>)}</TableRow>
          <TableRow><TableCell><MetricLabel>Drawdown</MetricLabel></TableCell>{series.map(s=><TableCell key={s.key} className="numeric">{pct(part[s.key].maxDrawdown)}</TableCell>)}</TableRow>
          {([{key:'volatilityPct',label:'Volatility',suffix:'%'},{key:'sharpe',label:'Sharpe ratio',suffix:''},{key:'beta',label:'Beta',suffix:''},{key:'correlation',label:'Correlation',suffix:''}] as const).map(m=><TableRow key={m.key}><TableCell><MetricLabel>{m.label}</MetricLabel></TableCell>{series.map(s=><TableCell key={s.key} className="numeric">{metric(part[`${s.key}Risk`][m.key],m.suffix)}</TableCell>)}</TableRow>)}
        </TableBody></Table><div className="research-chart-note">Risk uses consecutive observed wealth changes after the first close. Entry costs are included in total return and drawdown. These metrics are not annualized; unequal intervals and small samples limit comparisons. N/A means variance or sample size does not support that metric.</div></section></details>
        <details className="product-details"><summary>Compare with another backtest</summary><ResearchComparison key={`comparison-${active.id}`} active={active} runs={runs} period={period}/></details>
        <details className="product-details"><summary>View the trades</summary><section className="panel"><div className="panel-heading"><h2>Strategy executions</h2><span className="subtle">Latest {Math.min(part.strategy.trades.length,50)} · all executions in JSON</span></div>{part.strategy.trades.length?<Table><TableHeader><TableRow><TableHead>Signal close</TableHead><TableHead>Execution close</TableHead><TableHead>Action</TableHead><TableHead className="numeric">Shares</TableHead><TableHead className="numeric">Gross amount</TableHead><TableHead className="numeric">Fee</TableHead></TableRow></TableHeader><TableBody>{part.strategy.trades.slice(-50).reverse().map((t,i)=><TableRow key={i}><TableCell>{t.signalDate}</TableCell><TableCell>{t.date}</TableCell><TableCell>{t.side}</TableCell><TableCell className="numeric" title={t.shares}>{shareLabel(t.shares)}</TableCell><TableCell className="numeric">{money(t.gross)}</TableCell><TableCell className="numeric">{money(t.fee)}</TableCell></TableRow>)}</TableBody></Table>:<p className="actions-message">The rule stayed in cash throughout this evaluation period.</p>}</section></details>
        <details className="product-details"><summary>Data & calculation details</summary><section className="panel research-provenance"><div className="panel-heading"><h2><ShieldCheck size={18}/> Frozen inputs & methodology</h2><Button variant="outline" onClick={onOpenData}><Database size={16}/> Historical data</Button></div><div className="portfolio-inputs">{(['asset','benchmark'] as const).map(role=>{const b=active.snapshot[role];return <div key={role}><strong>{role==='asset'?'Strategy asset':'Benchmark'} · {b.dataset.symbol}</strong><p>{b.dataset.source} · {b.dataset.kind==='synthetic'?'Fictional':'Historical'} · USD raw closes</p><p>Events: {b.actions.source} · revision {b.actions.revision}</p><code>{b.dataset.id}</code></div>;})}<code>Run {active.id} · {active.snapshot.method}</code><p>Saved {new Date(active.created).toISOString()}. Later dataset or event edits do not change this experiment.</p><details><summary>Read all assumptions</summary>{Object.entries(RESEARCH_ASSUMPTIONS).map(([key,value])=><p key={key}><strong>{key}: </strong>{value}</p>)}</details></div></section>
        <p className="portfolio-method">A later period is a chronological check, not proof of predictive skill. Repeated experiments can overfit it. Event completeness and instrument selection are user-declared. No liquidity, market-impact or survivorship-bias correction is modeled.</p></details>
      </>}
    </>}
    <Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value);}}><DialogContent className="import-dialog portfolio-dialog"><DialogHeader><DialogTitle>Create a backtest</DialogTitle><DialogDescription>Choose a stock. We’ll test a simple rule that follows its recent price trend.</DialogDescription></DialogHeader>
      <form className="import-form" onSubmit={e=>{e.preventDefault();void submit('preview');}}><fieldset className="import-fields" disabled={busy}>
        <span className="step-label">1 · CHOOSE YOUR STOCK</span>
        <label>Stock to test<NativeSelect value={draft.assetId} required onChange={e=>{const chosen=datasets.find(d=>d.id===e.target.value);setAutoDates(true);setDateBusy(!!e.target.value);edit({window:chosen?Math.min(draft.window,Math.max(2,chosen.count-6)):draft.window,assetId:e.target.value,benchmarkId:draft.benchmarkId===draft.assetId||!draft.benchmarkId?e.target.value:draft.benchmarkId,start:'',end:'',holdoutStart:''});}}><option value="">Choose saved prices…</option>{datasets.filter(d=>d.basis==='raw'&&d.priceColumn==='close').map(d=><option key={d.id} value={d.id} disabled={d.count<8}>{d.symbol} · {d.firstDate} to {d.lastDate}{d.count<8?' · More prices needed':''}{d.kind==='synthetic'?' · Fictional':''}</option>)}</NativeSelect></label>
        {!datasets.some(d=>d.basis==='raw'&&d.priceColumn==='close')&&<p className="form-note">Add unadjusted daily prices in Prices &amp; data to begin.</p>}
        <label>Starting amount ($)<Input type="number" min="100" max="100000000" step="0.01" value={draft.initialCash} onChange={e=>edit({initialCash:e.target.value})} required/></label>
        <div className="default-summary"><strong>{dateBusy?'Choosing your dates…':'Ready with sensible starting settings'}</strong><p>{draft.start&&draft.end?`${draft.start} to ${draft.end} · `:''}{draft.window}-price trend window · {(draft.feeBps/100).toFixed(2)}% fee · {(draft.slippageBps/100).toFixed(2)}% price difference per trade.</p><p>Compared with buying and holding {datasets.find(d=>d.id===draft.benchmarkId)?.symbol??'the same stock'}.</p></div>
        <details className="settings-details"><summary>Customize this backtest</summary><div className="settings-fields">
          <label>Report name<Input value={draft.name} onChange={e=>edit({name:e.target.value})} minLength={2} maxLength={80} required/></label>
          <label><MetricLabel>Benchmark</MetricLabel><NativeSelect value={draft.benchmarkId} required onChange={e=>edit({benchmarkId:e.target.value})}><option value="">Choose a comparison…</option>{datasets.filter(d=>d.basis==='raw'&&d.priceColumn==='close').map(d=><option key={d.id} value={d.id}>{d.symbol} · {d.firstDate} to {d.lastDate}</option>)}</NativeSelect></label>
          <label><MetricLabel>Trend window</MetricLabel><Input type="number" min="2" max="500" step="1" value={draft.window} onChange={e=>{setAutoDates(true);setDateBusy(!!draft.assetId);edit({window:Number(e.target.value),start:'',end:'',holdoutStart:''});}} required/></label>
          <div className="form-grid"><label>Start date<Input type="date" value={draft.start} onChange={e=>{setAutoDates(false);setDateBusy(false);edit({start:e.target.value});}} required/></label><label>End date<Input type="date" value={draft.end} onChange={e=>{setAutoDates(false);setDateBusy(false);edit({end:e.target.value});}} required/></label><label>Later period starts<Input type="date" value={draft.holdoutStart} onChange={e=>{setAutoDates(false);setDateBusy(false);edit({holdoutStart:e.target.value});}} required/></label></div>
          <Button type="button" variant="outline" disabled={autoDates} onClick={()=>{setAutoDates(true);setDateBusy(!!draft.assetId);}}>Use available dates</Button>
          <div className="form-grid"><label>Trading fee (%)<Input type="number" min="0" max="10" step="0.01" value={draft.feeBps/100} onChange={e=>edit({feeBps:Math.round(Number(e.target.value)*100)})} required/></label><label><MetricLabel>Slippage</MetricLabel><span className="form-note">Price difference per trade (%)</span><Input type="number" min="0" max="10" step="0.01" value={draft.slippageBps/100} onChange={e=>edit({slippageBps:Math.round(Number(e.target.value)*100)})} required/></label></div>
          <p className="form-note">The rule buys when the previous price is above its moving average, and otherwise holds cash. Each period starts over with the same amount. Prices and company events must cover the chosen dates.</p>
        </div></details>
        <label className="actions-confirm"><Checkbox checked={draft.confirmed} onCheckedChange={value=>edit({confirmed:value===true})}/><span>I’ve checked that the prices and company events match the stock and dates I want to test.</span></label>
      </fieldset>
      {formError&&<p className="negative import-error" role="alert">{formError}</p>}
      {preview&&<div className="import-preview"><strong>Calculated preview · not saved yet</strong><p>Full-period strategy {pct(preview.analysis.full.strategy.returnPct)} · Buy & hold {pct(preview.analysis.full.buyHold.returnPct)} · Benchmark {pct(preview.analysis.full.benchmark.returnPct)}</p><p>Earlier strategy {pct(preview.analysis.development.strategy.returnPct)} · Later strategy {pct(preview.analysis.holdout.strategy.returnPct)}</p><small>{preview.analysis.synthetic?'Contains fictional price inputs. ':''}Save this result to revisit or share it.</small></div>}
      {preview&&<ConfidenceCertificate certificate={preview.confidence}/>}
      <div className="import-actions"><Button type="submit" variant={preview?'outline':'default'} disabled={busy||dateBusy||!draft.start||!draft.end}>{busy?'Calculating…':'See my result'}</Button>{preview&&<Button type="button" disabled={busy} onClick={()=>void submit('save')}>Save backtest</Button>}</div></form>
    </DialogContent></Dialog>
  </div>;
}
