'use client';
import ReportDownload from './report-download';
import { useEffect, useState } from 'react';
import { FlaskConical, Plus, Download, Database, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { NativeSelect } from '@/components/ui/native-select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { toast } from 'sonner';
import { RESEARCH_ASSUMPTIONS, type ResearchDraft, type ResearchAnalysis, type ResearchSegment, type SavedResearch, type RunSummary } from '@/lib/finance/research';
import type { DatasetSummary, SavedDataset } from '@/lib/finance/market-data';
import ConfidenceCertificate from './confidence-certificate';
import { researchCertificate, type ConfidenceCertificate as Certificate } from '@/lib/finance/confidence';
import BackgroundResearch from './background-research';
import ResearchComparison from './research-comparison';
const money=(s:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(s)/100);
const pct=(n:number)=>(n>0?'+':'')+n.toFixed(2)+'%';
const metric=(n:number|null,suffix='')=>n===null?'N/A':n.toFixed(3)+suffix;
function shareLabel(value:string){const [n,d='1']=value.split('/').map(BigInt);if(1000000n%BigInt(d)!==0n)return value;const units=n*1000000n/BigInt(d);return `${units/1000000n}.${(units%1000000n).toString().padStart(6,'0')}`.replace(/\.?0+$/,'');}
async function read<T>(res:Response):Promise<T>{const d=await res.json() as {error?:string};if(!res.ok)throw new Error(d.error||'Research request failed.');return d as T;}
const fresh=():ResearchDraft=>({name:'Moving-average research',assetId:'',benchmarkId:'',start:'',end:'',holdoutStart:'',window:20,initialCash:'10000',feeBps:10,slippageBps:5,confirmed:false});
const series=[{key:'strategy',name:'SMA strategy',color:'#20775b'},{key:'buyHold',name:'Asset buy & hold',color:'#bd9245'},{key:'benchmark',name:'Benchmark',color:'#657fb5'}] as const;
function ResearchChart({part,initial}:{part:ResearchSegment;initial:string}) {
  const rows=part.strategy.history,values=series.flatMap(s=>part[s.key].history.map(p=>Number(p.value)/100)),lo=Math.min(Number(initial),...values),hi=Math.max(Number(initial),...values),pad=Math.max((hi-lo)*.12,1);
  const start=Date.parse(part.start),end=Date.parse(part.end),x=(i:number)=>85+(Date.parse(rows[i].date)-start)/Math.max(1,end-start)*725,y=(v:number)=>18+(hi+pad-v)/(hi-lo+2*pad)*225;
  return <div className="portfolio-chart"><div className="actions-legend">{series.map(s=><span key={s.key}><i style={{background:s.color}}/>{s.name}</span>)}</div><svg viewBox="0 0 850 285" role="img" aria-label={`Hypothetical wealth in USD from ${part.start} to ${part.end}. Exact observations are available in the CSV report.`}>
    {[0,.5,1].map(f=>{const v=lo+(hi-lo)*f;return <g key={f}><line x1="85" x2="810" y1={y(v)} y2={y(v)} stroke="#e3e9e5" strokeDasharray="3 5"/><text x="74" y={y(v)+4} textAnchor="end" fontSize="12" fill="#607367">{v.toLocaleString('en-US',{maximumFractionDigits:0})}</text></g>;})}
    {series.slice().reverse().map(s=><path key={s.key} d={part[s.key].history.map((p,i)=>`${i?'L':'M'}${x(i)},${y(Number(p.value)/100)}`).join(' ')} fill="none" stroke={s.color} strokeWidth={s.key==='strategy'?3:2} strokeDasharray={s.key==='benchmark'?'6 4':undefined}/>)}
    <text x="85" y="278" fontSize="12" fill="#607367">{part.start}</text><text x="810" y="278" fontSize="12" fill="#607367" textAnchor="end">{part.end}</text></svg></div>;
}
export default function ResearchLab({onOpenData}:{onOpenData:()=>void}) {
  const [runs,setRuns]=useState<RunSummary[]>([]),[datasets,setDatasets]=useState<DatasetSummary[]>([]),[selected,setSelected]=useState(''),[run,setRun]=useState<SavedResearch|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
  const [open,setOpen]=useState(false),[draft,setDraft]=useState<ResearchDraft>(fresh),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[preview,setPreview]=useState<{analysis:ResearchAnalysis;fingerprint:string;confidence:Certificate}|null>(null),[period,setPeriod]=useState<'full'|'development'|'holdout'>('full');
  useEffect(()=>{const c=new AbortController();void Promise.all([fetch('/api/research',{cache:'no-store',signal:c.signal}).then(read<{runs:RunSummary[]}>),fetch('/api/datasets',{cache:'no-store',signal:c.signal}).then(read<{datasets:DatasetSummary[]}>)]).then(([r,d])=>{if(!c.signal.aborted){setRuns(r.runs);setDatasets(d.datasets);setSelected(s=>s||r.runs[0]?.id||'');}}).catch(e=>{if(!c.signal.aborted)setError((e as Error).message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[refresh]);
  useEffect(()=>{if(!selected)return;const c=new AbortController();void fetch(`/api/research?id=${selected}`,{cache:'no-store',signal:c.signal}).then(read<{run:SavedResearch}>).then(d=>{if(!c.signal.aborted)setRun(d.run);}).catch(e=>{if(!c.signal.aborted)setError((e as Error).message);});return()=>c.abort();},[selected,refresh]);
  function reload(){setLoading(true);setError('');setRefresh(n=>n+1);}
  function start(){setDraft(run?{...run.snapshot.config,name:run.name+' copy',confirmed:false}:fresh());setPreview(null);setFormError('');setOpen(true);}
  function edit(patch:Partial<ResearchDraft>){setDraft(d=>({...d,...patch,confirmed:patch.confirmed??false}));setPreview(null);setFormError('');}
  async function chooseDates(){if(!draft.assetId)return;setBusy(true);setFormError('');try{const dataset=await fetch(`/api/datasets?id=${draft.assetId}`,{cache:'no-store'}).then(read<SavedDataset>),points=dataset.observations.slice(draft.window);if(points.length<6)throw new Error('This window needs more history: allow the SMA warmup plus at least six evaluation observations.');edit({start:points[0].date,end:points.at(-1)!.date,holdoutStart:points[Math.min(points.length-3,Math.max(3,Math.floor(points.length*.7)))].date});}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
  async function submit(mode:'preview'|'save'){setBusy(true);setFormError('');try{const res=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,draft,fingerprint:preview?.fingerprint})});if(mode==='preview')setPreview(await read<{analysis:ResearchAnalysis;fingerprint:string;confidence:Certificate}>(res));else{const result=await read<{run:SavedResearch;message:string}>(res);setRun(result.run);setSelected(result.run.id);setPeriod('full');setRuns(r=>[result.run,...r.filter(v=>v.id!==result.run.id)]);setOpen(false);toast.success(result.message);}}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
  const active=run?.id===selected?run:null,part=active?.analysis[period];
  return <div className="research-workspace">
    <div className="portfolio-toolbar"><div><h2>From a rule to a reproducible result.</h2><p>Compare one fixed strategy with buy-and-hold and a benchmark.</p></div><Button onClick={start} disabled={loading}><Plus size={16}/> New experiment</Button></div>
    {error&&<div className="error-banner" role="alert">{error}<button onClick={reload}>Retry</button></div>}
    {loading?<div className="panel empty-state" role="status">Loading saved research…</div>:<>
      {runs.length>0&&<div className="research-picker"><label htmlFor="research-run">Saved experiment</label><NativeSelect id="research-run" value={selected} onChange={e=>{setSelected(e.target.value);setError('');setPeriod('full');}}>{runs.map(r=><option key={r.id} value={r.id}>{r.name} · {r.symbol} / {r.benchmark} · {r.id.slice(0,8)}</option>)}</NativeSelect><span>{runs.length} / 30 saved</span></div>}
      {!runs.length&&!error&&<section className="panel research-empty"><FlaskConical size={36}/><h2>A testable idea, with the assumptions attached.</h2><p>Choose saved prices, a moving-average window and trading costs. Inspect the full period and a separate later period, then preserve the experiment.</p><div><Button onClick={start}>Create an experiment</Button><Button variant="outline" onClick={onOpenData}>Prepare historical data</Button></div><p className="research-muted">USD raw closes and a complete split/dividend record are required for both inputs. You may use the same asset as its own benchmark.</p></section>}
      {selected&&!active&&!error&&<div className="panel empty-state" role="status">Loading frozen experiment…</div>}
      {active&&part&&<>
        <BackgroundResearch key={active.id} id={active.id}/>
        <div className="portfolio-toolbar"><div><h2>{active.name}</h2><p>{active.symbol} · SMA {active.snapshot.config.window} observations · {active.snapshot.config.feeBps} bps fee + {active.snapshot.config.slippageBps} bps slippage per trade</p></div><div><Button variant="outline" asChild><ReportDownload href={`/api/research?id=${active.id}&download=json`} download><Download size={16}/> Full report JSON</ReportDownload></Button><Button variant="outline" asChild><ReportDownload href={`/api/research?id=${active.id}&download=csv`} download>Observations CSV</ReportDownload></Button></div></div>
        <div className="research-periods" aria-label="Evaluation period">{([{key:'full',label:'Full period'},{key:'development',label:'Earlier period'},{key:'holdout',label:'Later period · fresh cash'}] as const).map(p=><Button key={p.key} variant={period===p.key?'default':'outline'} aria-pressed={period===p.key} onClick={()=>setPeriod(p.key)}>{p.label}</Button>)}</div>
        <ConfidenceCertificate certificate={researchCertificate(active,period)}/>
        <div className="portfolio-metrics"><div><span>Strategy return</span><strong className={part.strategy.returnPct>=0?'positive':'negative'}>{pct(part.strategy.returnPct)}</strong><small>Includes fees, slippage and receivables</small></div><div><span>Benchmark return</span><strong>{pct(part.benchmark.returnPct)}</strong><small>{active.benchmark} · modeled buy-and-hold</small></div><div><span>Outperformance</span><strong>{part.outperformancePct.toFixed(2)} pp</strong><small>Strategy minus benchmark return</small></div><div><span>Observed drawdown</span><strong>{pct(part.strategy.maxDrawdown)}</strong><small>Strategy · from prior observed peak</small></div><div><span>Strategy ending value</span><strong>{money(part.strategy.history.at(-1)!.value)}</strong><small>Initial cash ${Number(active.snapshot.config.initialCash).toLocaleString('en-US')}</small></div><div><span>Executed trades</span><strong>{part.strategy.trades.length}</strong><small>{money(part.strategy.fees)} fees · no forced final liquidation</small></div></div>
        <section className="panel"><div className="panel-heading"><div><h2>Three paths, the same starting cash</h2><p>{part.start} → {part.end} · {part.observations} observations</p></div><span className="research-kind">{active.analysis.synthetic?'SYNTHETIC INPUTS':'HYPOTHETICAL RESEARCH'}</span></div><ResearchChart part={part} initial={active.snapshot.config.initialCash}/><div className="research-chart-note">Wealth includes cash, stock and unpaid dividend entitlements. Lines connect supplied closes. Both evaluation segments restart with fresh cash; earlier observations only warm up signals.</div></section>
        <section className="panel"><div className="panel-heading"><div><h2>Return & risk comparison</h2><p>{part.strategyRisk.intervals} matched intervals · longest gap {part.longestGapDays} calendar days</p></div></div><Table><TableHeader><TableRow><TableHead>Measure</TableHead>{series.map(s=><TableHead className="numeric" key={s.key}>{s.name}</TableHead>)}</TableRow></TableHeader><TableBody>
          <TableRow><TableCell>Return after costs</TableCell>{series.map(s=><TableCell key={s.key} className="numeric">{pct(part[s.key].returnPct)}</TableCell>)}</TableRow>
          <TableRow><TableCell>Largest observed drawdown</TableCell>{series.map(s=><TableCell key={s.key} className="numeric">{pct(part[s.key].maxDrawdown)}</TableCell>)}</TableRow>
          {([{key:'volatilityPct',label:'Volatility per observed interval',suffix:'%'},{key:'sharpe',label:'Sharpe per observed interval · 0% cash',suffix:''},{key:'beta',label:'Beta vs selected benchmark',suffix:''},{key:'correlation',label:'Correlation with benchmark',suffix:''}] as const).map(m=><TableRow key={m.key}><TableCell>{m.label}</TableCell>{series.map(s=><TableCell key={s.key} className="numeric">{metric(part[`${s.key}Risk`][m.key],m.suffix)}</TableCell>)}</TableRow>)}
        </TableBody></Table><div className="research-chart-note">Risk uses consecutive observed wealth changes after the first close. Entry costs are included in total return and drawdown. These metrics are not annualized; unequal intervals and small samples limit comparisons. N/A means variance or sample size does not support that metric.</div></section>
        <ResearchComparison key={`comparison-${active.id}`} active={active} runs={runs} period={period}/>
        <section className="panel"><div className="panel-heading"><h2>Strategy executions</h2><span className="subtle">Latest {Math.min(part.strategy.trades.length,50)} · all executions in JSON</span></div>{part.strategy.trades.length?<Table><TableHeader><TableRow><TableHead>Signal close</TableHead><TableHead>Execution close</TableHead><TableHead>Action</TableHead><TableHead className="numeric">Shares</TableHead><TableHead className="numeric">Gross amount</TableHead><TableHead className="numeric">Fee</TableHead></TableRow></TableHeader><TableBody>{part.strategy.trades.slice(-50).reverse().map((t,i)=><TableRow key={i}><TableCell>{t.signalDate}</TableCell><TableCell>{t.date}</TableCell><TableCell>{t.side}</TableCell><TableCell className="numeric" title={t.shares}>{shareLabel(t.shares)}</TableCell><TableCell className="numeric">{money(t.gross)}</TableCell><TableCell className="numeric">{money(t.fee)}</TableCell></TableRow>)}</TableBody></Table>:<p className="actions-message">The rule stayed in cash throughout this evaluation period.</p>}</section>
        <section className="panel research-provenance"><div className="panel-heading"><h2><ShieldCheck size={18}/> Frozen inputs & methodology</h2><Button variant="outline" onClick={onOpenData}><Database size={16}/> Historical data</Button></div><div className="portfolio-inputs">{(['asset','benchmark'] as const).map(role=>{const b=active.snapshot[role];return <div key={role}><strong>{role==='asset'?'Strategy asset':'Benchmark'} · {b.dataset.symbol}</strong><p>{b.dataset.source} · {b.dataset.kind==='synthetic'?'Fictional':'Historical'} · USD raw closes</p><p>Events: {b.actions.source} · revision {b.actions.revision}</p><code>{b.dataset.id}</code></div>;})}<code>Run {active.id} · {active.snapshot.method}</code><p>Saved {new Date(active.created).toISOString()}. Later dataset or event edits do not change this experiment.</p><details><summary>Read all assumptions</summary>{Object.entries(RESEARCH_ASSUMPTIONS).map(([key,value])=><p key={key}><strong>{key}: </strong>{value}</p>)}</details></div></section>
        <p className="portfolio-method">A later period is a chronological check, not proof of predictive skill. Repeated experiments can overfit it. Event completeness and instrument selection are user-declared. No liquidity, market-impact or survivorship-bias correction is modeled.</p>
      </>}
    </>}
    <Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value);}}><DialogContent className="import-dialog portfolio-dialog"><DialogHeader><DialogTitle>Create a research experiment</DialogTitle><DialogDescription>Long when close is above its trailing SMA, otherwise cash. Each signal executes at the next supplied close.</DialogDescription></DialogHeader>
      <form className="import-form" onSubmit={e=>{e.preventDefault();void submit('preview');}}><fieldset className="import-fields" disabled={busy}>
        <label>Experiment name<Input value={draft.name} onChange={e=>edit({name:e.target.value})} minLength={2} maxLength={80} required/></label>
        <div className="form-grid">{([{key:'assetId',label:'Strategy asset dataset'},{key:'benchmarkId',label:'Benchmark dataset'}] as const).map(f=><label key={f.key}>{f.label}<NativeSelect value={draft[f.key]} required onChange={e=>edit({[f.key]:e.target.value})}><option value="">Choose raw close data…</option>{datasets.filter(d=>d.basis==='raw'&&d.priceColumn==='close').map(d=><option key={d.id} value={d.id}>{d.symbol} · {d.firstDate} → {d.lastDate} · {d.kind==='synthetic'?'Fictional':'Historical'} · {d.id.slice(0,8)}</option>)}</NativeSelect></label>)}</div>
        <div className="form-grid"><label>SMA window (observations)<Input type="number" min="2" max="500" step="1" value={draft.window} onChange={e=>edit({window:Number(e.target.value)})} required/></label><label>Initial cash (USD)<Input type="number" min="100" max="100000000" step="0.01" value={draft.initialCash} onChange={e=>edit({initialCash:e.target.value})} required/></label></div>
        <Button type="button" variant="outline" disabled={!draft.assetId} onClick={()=>void chooseDates()}>Use available dates after warmup</Button>
        <div className="form-grid"><label>Evaluation start<Input type="date" value={draft.start} onInput={e=>edit({start:e.currentTarget.value})} required/></label><label>Later-period start<Input type="date" value={draft.holdoutStart} onInput={e=>edit({holdoutStart:e.currentTarget.value})} required/></label><label>Evaluation end<Input type="date" value={draft.end} onInput={e=>edit({end:e.currentTarget.value})} required/></label></div>
        <div className="form-grid"><label>Fee per trade (basis points)<Input type="number" min="0" max="1000" step="1" value={draft.feeBps} onChange={e=>edit({feeBps:Number(e.target.value)})} required/></label><label>Slippage per trade (basis points)<Input type="number" min="0" max="1000" step="1" value={draft.slippageBps} onChange={e=>edit({slippageBps:Number(e.target.value)})} required/></label></div>
        <p className="form-note">100 basis points = 1%. Both inputs need complete saved event records and identical observation dates during evaluation. Allow the SMA window before the start, plus at least three observations in each segment. Later-period cash resets; dividends remain nonspendable receivables. No automatic parameter search.</p>
        <label className="actions-confirm"><Checkbox checked={draft.confirmed} onCheckedChange={value=>edit({confirmed:value===true})}/><span>I checked instrument identity and event coverage, and understand the execution, cost and evaluation conventions.</span></label>
      </fieldset>
      {formError&&<p className="negative import-error" role="alert">{formError}</p>}
      {preview&&<div className="import-preview"><strong>Calculated preview · not saved yet</strong><p>Full-period strategy {pct(preview.analysis.full.strategy.returnPct)} · Buy & hold {pct(preview.analysis.full.buyHold.returnPct)} · Benchmark {pct(preview.analysis.full.benchmark.returnPct)}</p><p>Earlier strategy {pct(preview.analysis.development.strategy.returnPct)} · Later strategy {pct(preview.analysis.holdout.strategy.returnPct)}</p><small>{preview.analysis.synthetic?'Contains fictional price inputs. ':''}Saving freezes all inputs, settings, trades and results.</small></div>}
      {preview&&<ConfidenceCertificate certificate={preview.confidence}/>}
      <div className="import-actions"><Button type="submit" variant={preview?'outline':'default'} disabled={busy}>{busy?'Calculating…':'Run preview'}</Button>{preview&&<Button type="button" disabled={busy} onClick={()=>void submit('save')}>Save experiment</Button>}</div></form>
    </DialogContent></Dialog>
  </div>;
}
