'use client';
import Link from 'next/link';
import MetricLabel from './metric-label';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import type { SharedResearch } from '@/lib/finance/shared-research';
import type { EvaluationPeriod } from '@/lib/finance/confidence';
import ConfidenceCertificate from './confidence-certificate';
import EquityChart from './equity-chart';
import './research-sharing.css';
const money=(value:string)=>{const n=BigInt(value),a=n<0n?-n:n;return `${n<0n?'−':''}$${(a/100n).toLocaleString('en-US')}.${(a%100n).toString().padStart(2,'0')}`;};
export default function SharedResearchView({report,expires,preview=false,example=false,invited=false}:{report:SharedResearch;expires?:string;preview?:boolean;example?:boolean;invited?:boolean}) {
  const [period,setPeriod]=useState<EvaluationPeriod>('full'),p=report.analysis[period];
  function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='marketlab-shared-summary.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <div className={`shared-research${preview?' shared-preview':''}`}>
    <header className="shared-header"><Link href="/" className="shared-wordmark">MarketLab<span>.</span></Link><span>{example?'SAMPLE REPORT':preview?'SHARING PREVIEW':'SHARED REPORT'}</span></header>
    {example&&<p className="share-boundary">Explore a sample report made with fictional prices and $10,000 in hypothetical cash.</p>}
    <div className="shared-title"><span className="shared-kicker">{report.analysis.synthetic?'FICTIONAL EXAMPLE':'HYPOTHETICAL RESULT'}</span><h1>{report.symbol} · Following the trend</h1><p>A simple trend strategy, compared with buying and holding.</p><details className="settings-details"><summary>Investment settings</summary><div className="settings-fields"><p>${Number(report.settings.initialCash).toLocaleString('en-US')} to start · {report.settings.window} earlier prices in the moving average · {report.benchmark} benchmark.</p><p>{(report.settings.feeBps/100).toFixed(2)}% trading fee · {(report.settings.slippageBps/100).toFixed(2)}% <MetricLabel>Slippage</MetricLabel> per trade.</p></div></details>{expires&&<p>Link expires {new Date(expires).toISOString().slice(0,16).replace('T',' ')} UTC. The owner can revoke it earlier.</p>}</div>
    <div className="research-periods" aria-label="Shared report evaluation period">{([{id:'full',label:'Full period'},{id:'development',label:'Earlier period'},{id:'holdout',label:'Later period'}] as const).map(v=><Button key={v.id} variant={period===v.id?'default':'outline'} aria-pressed={period===v.id} onClick={()=>setPeriod(v.id)}>{v.label}</Button>)}</div>
    <ConfidenceCertificate certificate={report.certificates[period]}/>
    <section className="panel"><div className="panel-heading"><div><h2>How the investment would have changed</h2><p>{p.start} → {p.end} · {p.observations} price dates</p></div></div><EquityChart key={period} part={p} initial={report.settings.initialCash} events={report.assetEvents}/><p className="research-chart-note">Each period starts with ${Number(report.settings.initialCash).toLocaleString('en-US')} in hypothetical cash. Compare the strategy with simply buying and holding.</p></section>
    <section className="panel"><div className="panel-heading"><h2>Results after modeled costs</h2></div><Table><TableHeader><TableRow><TableHead>Path</TableHead><TableHead><MetricLabel help="The value of the investment at the end, including cash and any earned dividends.">Ending value</MetricLabel></TableHead><TableHead><MetricLabel>Return</MetricLabel></TableHead><TableHead><MetricLabel>Drawdown</MetricLabel></TableHead></TableRow></TableHeader><TableBody>{([{key:'strategy',label:'Trend strategy'},{key:'buyHold',label:'Buy and hold'},{key:'benchmark',label:'Benchmark'}] as const).map(v=><TableRow key={v.key}><TableCell>{v.label}</TableCell><TableCell>{money(p[v.key].history.at(-1)!.value)}</TableCell><TableCell>{p[v.key].returnPct.toFixed(2)}%</TableCell><TableCell>{p[v.key].maxDrawdown.toFixed(2)}%</TableCell></TableRow>)}</TableBody></Table></section>
    <details className="shared-observations"><summary>Inspect exact observations ({p.observations})</summary><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Strategy wealth</TableHead><TableHead>Buy & hold</TableHead><TableHead>Benchmark</TableHead></TableRow></TableHeader><TableBody>{p.strategy.history.map((v,i)=><TableRow key={v.date}><TableCell>{v.date}</TableCell><TableCell>{money(v.value)}</TableCell><TableCell>{money(p.buyHold.history[i].value)}</TableCell><TableCell>{money(p.benchmark.history[i].value)}</TableCell></TableRow>)}</TableBody></Table></details>
    <footer className="shared-footer">{example&&<Button asChild><Link href="/">Try the interactive example</Link></Button>}<Button variant={example?"outline":"default"} onClick={download}>Download report (JSON)</Button><p>This report preserves the settings and results from when it was saved.</p><p>{invited?'Use your invitation link to return to this report and its discussion.':example?'Try changing costs in the interactive example on the home page.':'Anyone with this link can read this report while the link is active.'} A result is not a forecast.</p></footer>
  </div>;
}
