'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import type { SharedResearch } from '@/lib/finance/shared-research';
import type { EvaluationPeriod } from '@/lib/finance/confidence';
import ConfidenceCertificate from './confidence-certificate';
import EquityChart from './equity-chart';
import './research-sharing.css';
const money=(value:string)=>{const n=BigInt(value),a=n<0n?-n:n;return `${n<0n?'−':''}$${(a/100n).toLocaleString('en-US')}.${(a%100n).toString().padStart(2,'0')}`;};
export default function SharedResearchView({report,expires,preview=false,example=false,invited=false}:{report:SharedResearch;expires?:string;preview?:boolean;example?:boolean;invited?:boolean}) {
  const [period,setPeriod]=useState<EvaluationPeriod>('full'),p=report.analysis[period];
  function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='marketlab-shared-summary.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <div className={`shared-research${preview?' shared-preview':''}`}>
    <header className="shared-header"><span className="shared-wordmark">MarketLab<span>.</span></span><span>{example?'PUBLIC FICTIONAL EXAMPLE':preview?'PUBLIC PREVIEW':'READ-ONLY REPORT'}</span></header>
    {example&&<p className="share-boundary">This example uses invented prices and hypothetical cash. It contains no personal portfolio or account data.</p>}
    <div className="shared-title"><span className="shared-kicker">{report.analysis.synthetic?'CONTAINS FICTIONAL INPUTS':'HYPOTHETICAL RESEARCH'}</span><h1>{report.symbol} · Moving-average experiment</h1><p>{report.settings.window}-observation rule · {report.settings.feeBps} bps fees · {report.settings.slippageBps} bps slippage · benchmark {report.benchmark}</p>{expires&&<p>Link expires {new Date(expires).toISOString().slice(0,16).replace('T',' ')} UTC. The owner can revoke it earlier.</p>}</div>
    <div className="research-periods" aria-label="Shared report evaluation period">{([{id:'full',label:'Full period'},{id:'development',label:'Earlier period'},{id:'holdout',label:'Later period · fresh cash'}] as const).map(v=><Button key={v.id} variant={period===v.id?'default':'outline'} aria-pressed={period===v.id} onClick={()=>setPeriod(v.id)}>{v.label}</Button>)}</div>
    <ConfidenceCertificate certificate={report.certificates[period]}/>
    <section className="panel"><div className="panel-heading"><div><h2>Three paths, the same starting cash</h2><p>{p.start} → {p.end} · {p.observations} supplied observations</p></div></div><EquityChart key={period} part={p} initial={report.settings.initialCash} events={report.assetEvents}/><p className="research-chart-note">Each evaluation period starts with ${report.settings.initialCash} in hypothetical cash. Wealth includes stock, cash and unpaid dividend entitlements. Supplied closes are connected without filling missing dates.</p></section>
    <section className="panel"><div className="panel-heading"><h2>Results after modeled costs</h2></div><Table><TableHeader><TableRow><TableHead>Path</TableHead><TableHead>Ending value</TableHead><TableHead>Return</TableHead><TableHead>Observed drawdown</TableHead></TableRow></TableHeader><TableBody>{([{key:'strategy',label:'SMA strategy'},{key:'buyHold',label:'Asset buy & hold'},{key:'benchmark',label:'Benchmark'}] as const).map(v=><TableRow key={v.key}><TableCell>{v.label}</TableCell><TableCell>{money(p[v.key].history.at(-1)!.value)}</TableCell><TableCell>{p[v.key].returnPct.toFixed(2)}%</TableCell><TableCell>{p[v.key].maxDrawdown.toFixed(2)}%</TableCell></TableRow>)}</TableBody></Table></section>
    <details className="shared-observations"><summary>Inspect exact observations ({p.observations})</summary><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Strategy wealth</TableHead><TableHead>Buy & hold</TableHead><TableHead>Benchmark</TableHead></TableRow></TableHeader><TableBody>{p.strategy.history.map((v,i)=><TableRow key={v.date}><TableCell>{v.date}</TableCell><TableCell>{money(v.value)}</TableCell><TableCell>{money(p.buyHold.history[i].value)}</TableCell><TableCell>{money(p.benchmark.history[i].value)}</TableCell></TableRow>)}</TableBody></Table></details>
    <footer className="shared-footer"><Button variant="outline" onClick={download}>Download complete summary JSON</Button><p>This report is a saved snapshot of the experiment and its results.</p><p>{invited?'Use your invitation link to return to this report and its discussion.':example?'This built-in example is public and has no expiry. Owner-shared reports use separate expiring links that can be revoked.':'Anyone with this link can read and copy the summary. Revoking the link stops future access; it cannot remove copies someone already saved.'} A result is not a forecast.</p></footer>
  </div>;
}
