'use client';
import ReportDownload from './report-download';
import { useState, useEffect, useRef, useCallback } from 'react';
import { Activity, ArrowDownLeft, ArrowUpRight, ArrowRight, ChartNoAxesCombined, ChevronRight, CircleHelp, Database, Download, FlaskConical, LayoutDashboard, ListOrdered, Plus, RefreshCw, ShieldCheck, Wallet, Check, X, TrendingUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { NativeSelect } from '@/components/ui/native-select';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger, SidebarInset } from '@/components/ui/sidebar';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { assets, FIRST_DATE, LAST_DATE, type Workspace } from '@/lib/finance/demo';
import type { Transaction } from '@/lib/finance/core';
import MarketData from './market-data';
import StockExplorer from './stock-explorer';
import HistoricalPortfolio from './historical-portfolio';
import ResearchLab from './research-lab';
import ConfidenceCertificate from './confidence-certificate';
import { demoPortfolioCertificate } from '@/lib/finance/confidence';
import QuickDemo, { QuickDemoEntry } from './quick-demo';
function newRequestId(){
 const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;
 const h=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;
}
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const percent=(n:number)=>(n>=0?'+':'')+n.toFixed(2)+'%';
const dateLabel=(d:string)=>new Date(d+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'});
const menu=[{id:'explore',label:'Stock explorer',icon:ChartNoAxesCombined},{id:'market-data',label:'Historical data',icon:Database},{id:'portfolio',label:'My portfolio',icon:Wallet},{id:'research',label:'Research lab',icon:FlaskConical},{id:'quick-demo',label:'Quick experiment',icon:FlaskConical},{id:'overview',label:'Demo portfolio',icon:LayoutDashboard},{id:'transactions',label:'Demo transactions',icon:ListOrdered},{id:'pipeline',label:'Demo pipeline',icon:Database}];
const demoPages=['quick-demo','overview','transactions','pipeline'];
function Plot({points,comparison=false,mode='value',compact=false}:{points:{date:string;value:number;contributions?:number;returnPct?:number}[];comparison?:boolean;mode?:string;compact?:boolean}) {
 const [hover,setHover]=useState<number|null>(null);
 if(!points.length)return <p>No observations.</p>;
 const values=points.map(p=>mode==='return'?(p.returnPct??0):p.value);
 const extra=comparison&&mode==='value'?points.map(p=>p.contributions??0):[];
 const min=Math.min(...values,...extra), max=Math.max(...values,...extra), spread=Math.max(max-min,mode==='return'?1:100);
 const low=min-spread*.13, high=max+spread*.16, width=820,height=compact?160:245,left=compact?5:65,right=15,bottom=compact?10:35,top=12;
 const x=(i:number)=>left+i/Math.max(1,points.length-1)*(width-left-right);
 const y=(v:number)=>top+(high-v)/(high-low)*(height-top-bottom);
 const path=values.map((v,i)=>`${i?'L':'M'}${x(i)},${y(v)}`).join(' ');
 const idx=hover!==null?Math.min(hover,points.length-1):points.length-1;
 return <div className={'plot '+(compact?'compact':'')}>
  {!compact&&<div className="chart-caption"><span><i className="legend-dot"/> {mode==='return'?'Time-weighted return':'Portfolio value'}</span>{comparison&&mode==='value'&&<span><i className="legend-line"/> Net contributions</span>}<span className="chart-readout">{dateLabel(points[idx].date)} <strong>{mode==='return'?percent(values[idx]):money(values[idx])}</strong></span></div>}
  <svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Portfolio ${mode} from ${points[0].date} to ${points.at(-1)!.date}`} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();setHover(Math.max(0,Math.min(points.length-1,Math.round(((e.clientX-r.left)/r.width*width-left)/(width-left-right)*(points.length-1)))));}} onPointerLeave={()=>setHover(null)}>
   <defs><linearGradient id={compact?'smallFill':'chartFill'} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#208167" stopOpacity=".18"/><stop offset="100%" stopColor="#208167" stopOpacity="0"/></linearGradient></defs>
   {!compact&&Array.from({length:4},(_,i)=>{const v=low+(high-low)*i/3;return <g key={i}><line x1={left} x2={width-right} y1={y(v)} y2={y(v)} stroke="#e6eae8" strokeDasharray="3 4"/><text x={left-13} y={y(v)+4} textAnchor="end" fill="#7e8783" fontSize="12">{mode==='return'?v.toFixed(0)+'%':'$'+(v/1000).toFixed(0)+'k'}</text></g>;})}
   <path d={`${path} L${x(points.length-1)},${height-bottom} L${left},${height-bottom} Z`} fill={`url(#${compact?'smallFill':'chartFill'})`}/>
   {extra.length>0&&<path d={extra.map((v,i)=>`${i?'L':'M'}${x(i)},${y(v)}`).join(' ')} fill="none" stroke="#a5aea9" strokeWidth="1.7" strokeDasharray="5 5"/>}
   <path d={path} stroke="#1c795e" strokeWidth="2.6" fill="none" strokeLinejoin="round"/>
   {hover!==null&&<g><line x1={x(idx)} x2={x(idx)} y1={top} y2={height-bottom} stroke="#92aaa0" strokeDasharray="4 4"/><circle cx={x(idx)} cy={y(values[idx])} r="5" fill="#1c795e" stroke="white" strokeWidth="2"/></g>}
   {!compact&&[0,.25,.5,.75,1].map(f=>{const i=Math.round(f*(points.length-1));return <text key={f} x={x(i)} y={height-5} fill="#7e8783" fontSize="12" textAnchor={f===0?'start':f===1?'end':'middle'}>{dateLabel(points[i].date)}</text>;})}
  </svg>
 </div>;
}
async function api<T>(path:string,body?:unknown):Promise<T>{
 const res=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});
 const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error??'The request could not be completed.');return data as T;
}
export default function Dashboard({initial}:{initial:Workspace}){
 const [data,setData]=useState(initial),[page,setPage]=useState('explore'),[range,setRange]=useState('6M'),[mode,setMode]=useState('value'),[datasetId,setDatasetId]=useState(''),[selected,setSelected]=useState<string|null>(null),[showForm,setShowForm]=useState(false),[help,setHelp]=useState(false),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[loadError,setLoadError]=useState(''),[formError,setFormError]=useState(''),[kind,setKind]=useState<Transaction['kind']>('buy');
 const pendingId=useRef<string|null>(null);const [formSymbol,setFormSymbol]=useState('AAPL');
 const stateRef=useRef(data);useEffect(()=>{stateRef.current=data;},[data]);
 const reload=useCallback(async()=>{try{const next=await api<Workspace>('/api/workspace');setData(next);setReady(true);setLoadError('');return next;}catch(e){setLoadError((e as Error).message);throw e;}},[]);
 useEffect(()=>{let active=true;void api<Workspace>('/api/workspace').then(next=>{if(active){setData(next);setReady(true);setLoadError('');}}).catch(e=>{if(active)setLoadError((e as Error).message);});return()=>{active=false;};},[]);
 const replay=useCallback(async()=>{setBusy(true);try{const r=await api<{message:string}>('/api/pipeline',{});await reload();toast.success(r.message);return r;}catch(e){toast.error((e as Error).message);throw e;}finally{setBusy(false);}},[reload]);
 const openForm=(symbol?:unknown)=>{if(typeof symbol==='string')setFormSymbol(symbol);setFormError('');pendingId.current=newRequestId();setShowForm(true);};
 useEffect(()=>{
   type Registry={registerTool:(tool:Record<string,unknown>,options:{signal:AbortSignal})=>void|Promise<void>};
   const context=(document as Document&{modelContext?:Registry}).modelContext;if(!context)return;
   const lifecycle=new AbortController();
   const tools=[{name:'read_portfolio',description:'Read the current sample portfolio valuation and data status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');const d=stateRef.current;return {value:d.analytics.value,cash:d.analytics.cash,returnPct:d.analytics.returnPct,dataset:'synthetic-daily-v1',storedRows:d.pipeline.stored};}},
    {name:'navigate_workspace',description:'Open a portfolio workspace view. Does not change portfolio records.',inputSchema:{type:'object',properties:{page:{type:'string',enum:menu.map(m=>m.id)}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{const v=input as {page?:string};if(!v||Object.keys(v).some(k=>k!=='page')||!menu.some(m=>m.id===v.page))throw new Error('Choose quick-demo, research, portfolio, overview, explore, market-data, transactions, or pipeline.');setPage(v.page!);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {page:v.page};}}
   ];
   tools.forEach(tool=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}});return()=>lifecycle.abort();
 },[]);
 const a=data.analytics;
 const isDemo=demoPages.includes(page);
 const isPortfolioDemo=['overview','transactions','pipeline'].includes(page);
 function openQuickDemo(){setPage('quick-demo');window.scrollTo({top:0,behavior:'instant'});}
 function openDataset(id:string){setDatasetId(id);setPage('market-data');}
 const history=range==='6M'?a.history:a.history.slice(-({'1M':22,'3M':66}[range]??a.history.length));
 const selectedAsset=assets.find(x=>x.symbol===selected);
 const selectedQuotes=data.quotes.filter(q=>q.symbol===selected).sort((x,y)=>x.date.localeCompare(y.date));
 const title=menu.find(x=>x.id===page)?.label??'Overview';
 const alloc=[...a.holdings.map(h=>({name:h.symbol,value:h.value,color:assets.find(x=>x.symbol===h.symbol)!.color})),{name:'Cash',value:a.cash,color:'#d8dedb'}];
 let cumulative=0;const segments=alloc.map(x=>{const start=cumulative;cumulative+=x.value/a.value*100;return `${x.color} ${start}% ${cumulative}%`;}).join(',');
 async function saveTransaction(e:React.FormEvent<HTMLFormElement>){
  e.preventDefault();setBusy(true);setFormError('');const fd=new FormData(e.currentTarget);
  try{await api('/api/transactions',{id:pendingId.current,version:data.version,kind,date:fd.get('date'),symbol:fd.get('symbol')??'',shares:fd.get('shares')??'0',price:fd.get('price')??'0',amount:fd.get('amount')??'0',fee:fd.get('fee')??'0'});await reload();setShowForm(false);toast.success('Transaction saved. Portfolio recalculated.');}
  catch(e){setFormError((e as Error).message);}finally{setBusy(false);}
 }
 return <SidebarProvider style={{'--sidebar-width':'226px'} as React.CSSProperties}><Toaster position="bottom-right"/>
  <Sidebar className="app-sidebar"><SidebarHeader className="brand-area"><button type="button" onClick={()=>setPage('explore')} className="brand"><span className="brand-mark"><ChartNoAxesCombined size={22}/></span>MarketLab<span className="brand-period">.</span></button></SidebarHeader>
  <SidebarContent><div className="portfolio-switch"><span className="account-icon"><Wallet size={17}/></span><div>Market research<small>USD · Personal workspace</small></div><span className="account-dot"/></div>{[false,true].map(demo=><div key={String(demo)}><p className="nav-label">{demo?'DEMO · FICTIONAL DATA':'WORKSPACE'}</p><SidebarMenu className="nav-menu">{menu.filter(m=>demoPages.includes(m.id)===demo).map(m=><SidebarMenuItem key={m.id}><SidebarMenuButton isActive={page===m.id} onClick={()=>setPage(m.id)} className="nav-item"><m.icon size={18}/><span>{m.label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></div>)}
  <div className="sidebar-note"><FlaskConical size={18}/><strong>A place to test ideas.</strong><p>Explore market history, build a portfolio and test research ideas.</p><button onClick={()=>setHelp(true)}>How it works <ArrowUpRight size={14}/></button></div></SidebarContent>
  <SidebarFooter><button className="method-link" onClick={()=>setHelp(true)}><CircleHelp size={17}/>Methodology</button><div className="profile"><div className="avatar">ML</div><div>Personal workspace<small>Independent research project</small></div></div></SidebarFooter></Sidebar>
  <SidebarInset><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-trigger"/><span>Workspace</span><ChevronRight size={14}/><strong>{title}</strong></div><div className="top-meta"><span className="demo-tag"><FlaskConical size={13}/> {page==='portfolio'?'YOUR LEDGER':page==='explore'?'PROVIDER PRICES':['market-data','research'].includes(page)?'DATA RESEARCH':'FICTIONAL DEMO'}</span><span>USD</span></div></header>
  <main className="workspace">
   <div className="page-heading"><div><div className="eyebrow">{isDemo?'DEMO WORKSPACE':'YOUR RESEARCH WORKSPACE'}</div><h1>{title}</h1><p>{page==='quick-demo'?'See how one assumption changes a result.':page==='research'?'Test a rule, compare the outcomes and preserve the evidence.':page==='portfolio'?'Your transactions, saved market data and reconciled performance.':page==='overview'?'A fictional portfolio for exploring how the calculations work.':page==='explore'?'Provider-sourced daily closes with traceable dates and saved history.':page==='market-data'?'Import, validate and inspect historical price datasets.':page==='transactions'?'Sample trades and manual demo entries, valued with fictional prices.':'Validate and replay the fictional demo price dataset.'}</p></div>{isPortfolioDemo&&<div className="heading-actions"><Button variant="outline" asChild><ReportDownload href="/api/report" download aria-disabled={!ready}><Download/> Export demo report</ReportDownload></Button><Button onClick={openForm} disabled={!ready}><Plus/> Add demo transaction</Button></div>}</div>
   {loadError&&isPortfolioDemo&&<div className="error-banner" role="alert">Saved workspace unavailable: {loadError} Showing the sample portfolio. <button onClick={()=>void reload().catch(()=>{})}>Retry</button></div>}
   {isPortfolioDemo&&<ConfidenceCertificate certificate={demoPortfolioCertificate(data)}/>}
   {['explore','research'].includes(page)&&<QuickDemoEntry onStart={openQuickDemo}/>}
   {page==='quick-demo'&&<QuickDemo onOpenData={()=>setPage('market-data')}/>}
   {page==='research'&&<ResearchLab onOpenData={()=>setPage('market-data')}/>} {page==='market-data'&&<MarketData key={datasetId} initialDatasetId={datasetId}/>}{page==='portfolio'&&<HistoricalPortfolio onOpenData={()=>setPage('market-data')}/>}
   {isPortfolioDemo&&<div className="demo-notice"><FlaskConical size={21}/><div><strong>Fictional demo data</strong><p>These prices and sample positions are simulated. Use Stock explorer for provider prices, or My portfolio for your own historical ledger.</p></div><Button variant="outline" onClick={()=>setPage('explore')}>View market prices <ArrowRight size={15}/></Button></div>}
   {page==='overview'&&<>
    <section className="summary-strip" aria-label="Portfolio summary"><div className="primary-stat"><span>Total portfolio value</span><strong>{money(a.value)}</strong><small><span className={a.gain>=0?'positive':'negative'}><TrendingUp size={13}/> {money(a.gain)} total gain</span></small></div><div><span>Time-weighted return <button className="info-button" aria-label="Return methodology" onClick={()=>setHelp(true)}><CircleHelp size={13}/></button></span><strong className={a.returnPct>=0?'positive':'negative'}>{percent(a.returnPct)}</strong><small>Since Apr 1 · net of fees</small></div><div><span>Net contributions</span><strong>{money(a.contributions)}</strong><small>Deposits less withdrawals</small></div><div><span>Available cash</span><strong>{money(a.cash)}</strong><small>{(a.cash/a.value*100).toFixed(1)}% of portfolio</small></div></section>
    <div className="analytics-grid"><section className="panel performance"><div className="panel-heading"><div><h2>Portfolio performance</h2><p>Apr 1 – Sep 24, 2026</p></div><Tabs value={range} onValueChange={setRange}><TabsList><TabsTrigger value="1M">1M</TabsTrigger><TabsTrigger value="3M">3M</TabsTrigger><TabsTrigger value="6M">6M</TabsTrigger></TabsList></Tabs></div><div className="chart-mode"><button className={mode==='value'?'active':''} onClick={()=>setMode('value')}>Value</button><button className={mode==='return'?'active':''} onClick={()=>setMode('return')}>Return</button></div><Plot points={history} comparison mode={mode}/><div className="chart-footnote"><ShieldCheck size={14}/>{mode==='value'?'Contributions are shown separately from investment performance.':'Return is measured since inception; the range controls the visible dates.'}</div></section>
    <section className="panel allocation"><div className="panel-heading"><h2>Asset allocation</h2><span className="subtle">{a.holdings.length} assets</span></div><div className="donut" style={{background:`conic-gradient(${segments})`}} role="img" aria-label={alloc.map(x=>`${x.name} ${(x.value/a.value*100).toFixed(1)}%`).join(', ')}><div><span>Invested</span><strong>{((1-a.cash/a.value)*100).toFixed(1)}<small>%</small></strong></div></div><div className="allocation-list">{alloc.map(x=><div key={x.name}><span><i style={{background:x.color}}/>{x.name}</span><strong>{(x.value/a.value*100).toFixed(1)}%</strong></div>)}</div></section></div>
    <section className="panel holdings"><div className="panel-heading"><div className="heading-inline"><h2>Demo holdings</h2><span className="count">{a.holdings.length}</span></div><button className="text-link" onClick={()=>setPage('explore')}>View market prices <ArrowRight size={15}/></button></div><Table><TableHeader><TableRow><TableHead>Asset</TableHead><TableHead className="numeric">Shares</TableHead><TableHead className="numeric">Demo price</TableHead><TableHead className="numeric">Daily change</TableHead><TableHead className="numeric">Demo value</TableHead><TableHead className="numeric">Unrealized return</TableHead><TableHead className="numeric">Weight</TableHead></TableRow></TableHeader><TableBody>{a.holdings.map(h=>{const asset=assets.find(x=>x.symbol===h.symbol)!;return <TableRow key={h.symbol}><TableCell><button className="asset-name" onClick={()=>setSelected(h.symbol)}><span className="asset-monogram" style={{color:asset.color,background:asset.color+'15'}}>{h.symbol.slice(0,1)}</span><span><strong>{h.symbol}</strong><small>{asset.name}</small></span></button></TableCell><TableCell className="numeric">{h.units.toLocaleString('en-US',{maximumFractionDigits:6})}</TableCell><TableCell className="numeric">{money(h.price)}</TableCell><TableCell className={'numeric '+(h.dayPct>=0?'positive':'negative')}>{percent(h.dayPct)}</TableCell><TableCell className="numeric font-medium">{money(h.value)}</TableCell><TableCell className={'numeric '+(h.gainPct>=0?'positive':'negative')}>{percent(h.gainPct)}<small className="cell-small">{money(h.gain)}</small></TableCell><TableCell className="numeric">{(h.value/a.value*100).toFixed(1)}%</TableCell></TableRow>;})}</TableBody></Table></section>
   </>}
   {page==='explore'&&<StockExplorer onOpenDataset={openDataset}/>}
   {page==='transactions'&&<><div className="ledger-summary"><div><span>Total deposits, net</span><strong>{money(a.contributions)}</strong></div><div><span>Dividends received</span><strong>{money(a.dividends)}</strong></div><div><span>Fees paid</span><strong>{money(a.fees)}</strong></div><div><span>Realized gain</span><strong>{money(a.realized)}</strong></div></div><section className="panel"><div className="panel-heading"><h2>Demo transaction ledger <span className="count">{data.transactions.length}</span></h2><span className="subtle">Oldest records are preserved</span></div><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Transaction</TableHead><TableHead>Asset</TableHead><TableHead className="numeric">Shares</TableHead><TableHead className="numeric">Amount</TableHead><TableHead className="numeric">Fee</TableHead><TableHead>Source</TableHead></TableRow></TableHeader><TableBody>{[...data.transactions].reverse().map(t=><TableRow key={t.id}><TableCell>{dateLabel(t.date)}, 2026</TableCell><TableCell><span className={'kind-badge '+t.kind}>{t.kind==='deposit'||t.kind==='dividend'||t.kind==='sell'?<ArrowDownLeft size={13}/>:<ArrowUpRight size={13}/>} {t.kind}</span></TableCell><TableCell>{t.symbol||'USD'}</TableCell><TableCell className="numeric">{Number(t.units)===0?'—':(Number(t.units)/1e6).toLocaleString('en-US',{maximumFractionDigits:6})}</TableCell><TableCell className="numeric">{money(Number(t.amount)/100)}</TableCell><TableCell className="numeric">{money(Number(t.fee)/100)}</TableCell><TableCell><span className="subtle">{t.id.startsWith('seed-')?'Sample':'Manual entry'}</span></TableCell></TableRow>)}</TableBody></Table></section></>}
   {page==='pipeline'&&<><div className="pipeline-banner"><span className="pipeline-icon"><Database size={25}/></span><div><h2>Reproducible by design.</h2><p>Validate and ingest the same fictional dataset. Replays preserve one price per symbol and date.</p></div><Button onClick={()=>void replay().catch(()=>{})} disabled={busy}><RefreshCw className={busy?'animate-spin':''}/>{busy?'Processing…':'Run ingestion'}</Button></div><div className="pipeline-stats"><div className="panel"><span>Stored price observations</span><strong>{data.pipeline.stored.toLocaleString()}<small> / {data.pipeline.expected}</small></strong><p>{data.pipeline.stored===data.pipeline.expected?'Dataset complete':'Run ingestion to populate the database'}</p></div><div className="panel"><span>Source coverage</span><strong>{assets.length}<small> symbols</small></strong><p>Weekday fixtures · Apr 1 – Sep 24</p></div><div className="panel"><span>Data source</span><strong className="source-label">Synthetic v1</strong><p>Deterministic prices · no live connection</p></div></div><section className="panel"><div className="panel-heading"><h2>Pipeline runs</h2><span className="subtle">Actual ingestion results</span></div>{data.pipeline.runs.length?<Table><TableHeader><TableRow><TableHead>Started (UTC)</TableHead><TableHead>Status</TableHead><TableHead className="numeric">Validated</TableHead><TableHead className="numeric">New rows</TableHead><TableHead className="numeric">Duration</TableHead><TableHead>Result</TableHead></TableRow></TableHeader><TableBody>{data.pipeline.runs.map(r=><TableRow key={r.id}><TableCell>{new Date(r.started).toISOString().replace('T',' ').slice(0,19)}</TableCell><TableCell><span className={'run-badge '+(r.status==='completed'?'positive':'negative')}>{r.status==='completed'?<Check size={13}/>:<X size={13}/>} {r.status}</span></TableCell><TableCell className="numeric">{r.records}</TableCell><TableCell className="numeric">{r.inserted}</TableCell><TableCell className="numeric">{r.duration} ms</TableCell><TableCell>{r.message}</TableCell></TableRow>)}</TableBody></Table>:<div className="empty-state"><Activity size={28}/><strong>Your first run starts here.</strong><p>Run ingestion to validate and store {data.pipeline.expected} observations.</p></div>}</section><div className="pipeline-note"><ShieldCheck size={18}/><p><strong>What’s checked?</strong> Known symbols, valid dates, positive integer prices, complete coverage, and unique symbol/date pairs. Failed runs are recorded; a replay safely skips rows already stored.</p></div></>}
   <footer className="workspace-footer"><span><i className="tiny-dot"/> {page==='quick-demo'?'Fictional teaching experiment':page==='research'?'Saved experiments · frozen research inputs':page==='portfolio'?'Your ledger · frozen research inputs':page==='market-data'?'Historical datasets · source details preserved':page==='explore'?'Alpha Vantage · saved daily history':'Sample prices as of Sep 24, 2026'} <span className="footer-divider">/</span> {page==='quick-demo'?'Calculated in your browser':page==='research'?'Hypothetical strategy research':page==='portfolio'?'USD historical analysis':page==='market-data'?'Daily data on demand':page==='explore'?'Observation dates shown per symbol':'Synthetic portfolio prices'}</span><button onClick={()=>setPage(isPortfolioDemo?'pipeline':'market-data')}>Data provenance <ArrowUpRight size={13}/></button></footer>
  </main></SidebarInset>
  <Dialog open={showForm} onOpenChange={setShowForm}><DialogContent><DialogHeader><DialogTitle>Add a demo transaction</DialogTitle><DialogDescription>Record a transaction in the fictional demo portfolio. Demo value and history will recalculate.</DialogDescription></DialogHeader><form onSubmit={saveTransaction} className="transaction-form"><label>Transaction type<NativeSelect value={kind} onChange={e=>{setKind(e.target.value as Transaction['kind']);setFormError('');}}>{['buy','sell','deposit','withdrawal','dividend'].map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</NativeSelect></label><label>Date<Input name="date" type="date" defaultValue={LAST_DATE} min={FIRST_DATE} max={LAST_DATE} required/></label>{['buy','sell','dividend'].includes(kind)&&<label>Asset<NativeSelect name="symbol" value={formSymbol} onChange={e=>setFormSymbol(e.target.value)}>{assets.map(x=><option key={x.symbol} value={x.symbol}>{x.symbol} · {x.name}</option>)}</NativeSelect></label>}{kind==='buy'||kind==='sell'?<><div className="form-grid"><label>Shares<Input name="shares" type="number" min="0.000001" max="1000000" step="0.000001" placeholder="10" required/></label><label>Price per share ($)<Input name="price" type="number" min="0.01" max="1000000" step="0.01" placeholder="160.00" required/></label></div><label>Fee ($)<Input name="fee" type="number" min="0" max="1000000" step="0.01" defaultValue="0" required/></label></>:<label>Amount ($)<Input name="amount" type="number" min="0.01" max="1000000" step="0.01" placeholder="1000.00" required/></label>}<p className="form-note">This demo supports USD, long positions, and the displayed six-month window.</p>{formError&&<p className="negative" role="alert">{formError}</p>}<Button type="submit" disabled={busy} className="w-full">{busy?'Saving…':'Save demo transaction'}</Button></form></DialogContent></Dialog>
  <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="asset-dialog"><DialogHeader><DialogTitle>Demo · {selected} · {selectedAsset?.name}</DialogTitle><DialogDescription>{selectedAsset?.sector} · Synthetic daily prices</DialogDescription></DialogHeader><p className="demo-price-label">SIMULATED CLOSE · FICTIONAL DATA</p><div className="detail-price">{money(Number(selectedQuotes.at(-1)?.close??0)/100)}<span>as of Sep 24, 2026</span></div><Plot points={selectedQuotes.map(q=>({date:q.date,value:Number(q.close)/100}))} compact/><p className="form-note">Fictional research data. These observations do not represent actual market prices.</p><Button onClick={()=>{setSelected(null);openForm(selected);}}>Record a demo transaction <Plus size={16}/></Button></DialogContent></Dialog>
  <Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogHeader><DialogTitle>Know what your numbers mean.</DialogTitle><DialogDescription>MarketLab · Data and calculation methods</DialogDescription></DialogHeader><div className="methodology"><p><strong>Demo portfolio value</strong> is cash plus shares valued at the latest available closing price on or before each date. Missing initial prices stop valuation.</p><p><strong>Demo time-weighted return</strong> chains daily market returns and ledger-event returns. Events are valued at that day’s close in ledger order; deposits and withdrawals do not change the return. Fees and dividends affect it.</p><p><strong>Demo unrealized return</strong> uses average acquisition cost including buy fees. This is a research calculation, not a tax report.</p><p><strong>Demo boundaries</strong> Six fictional price series, weekday observations, USD only, no shorting or leverage. Historical data and My portfolio provide separate research using your saved prices and event records. Stock explorer reads saved provider closes; it does not stream quotes. Research lab tests strategies against frozen historical inputs.</p><p><strong>Saved records</strong> Manual transactions and ingestion results are stored server-side. The built-in sample ledger stays in the Demo section. Provider datasets and your historical portfolio are separate.</p></div></DialogContent></Dialog>
 </SidebarProvider>;
}
