import assert from 'node:assert/strict';
import {emptyPlan,emptyValues,type Plan,type SavedPlan} from '../lib/planning/core.ts';
import {priorQuarter} from '../lib/planning/community.ts';
import {researchFixture} from '../tests/fixtures/research.ts';
import {datasetId} from '../lib/finance/market-data.ts';
import {analyzeResearch,researchFingerprint,type SavedResearch} from '../lib/finance/research.ts';
import {replayReportJSON,replayDigest,REPLAY_VERSION} from '../lib/finance/replay-receipt.ts';
import type {PortfolioSnapshot} from '../lib/finance/historical-portfolio.ts';
type Headers=Record<string,string>;
type Request=(route:string,status:number|number[],init?:RequestInit)=>Promise<Response>;
export async function testPlanning({request,owner,visitor,db,runId}:{request:Request;owner:Headers;visitor:Headers;db:D1Database;runId:string}){
 let checks=0;const today=new Date().toISOString().slice(0,10),post=(body:unknown,headers=owner)=>({method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
 await request('/api/planning',401);await request('/api/planning',401,post({},{}));
 const p:Plan={...emptyPlan(),accounts:[{id:'account-a',name:'PRIVATE_PLANNING_NAME',kind:'brokerage',asOf:today,values:{...emptyValues(),stocks:'600000',bonds:'300000',cash:'100000'},debt:'0',feesPaid:'1234',annualFeeBps:25}],target:{stocks:5500,bonds:3500,cash:1000,crypto:0,property:0,other:0}};
 await request('/api/planning',200,post({revision:0,plan:p}));
 const own=await (await request('/api/planning?owner=other-user',200,{headers:owner})).json() as SavedPlan;assert.equal(own.plan.accounts[0].name,'PRIVATE_PLANNING_NAME');checks++;
 const other=await (await request('/api/planning?owner=hosted-fixture-owner',200,{headers:visitor})).json() as SavedPlan;assert.equal(other.revision,0);assert.equal(other.plan.accounts.length,0);checks+=2;
 await request('/api/planning',200,post({revision:0,plan:{...p,accounts:[{...p.accounts[0],name:'VISITOR_PLAN'}]}},visitor));
 await request('/api/planning',409,post({revision:0,plan:p}));await request('/api/planning',400,post({revision:1,plan:{...p,owner:'other-user'}}));
 const concurrent=await Promise.all([1,2].map(n=>request('/api/planning',[200,409],post({revision:1,plan:{...p,thresholdBps:n*100}}))));assert.deepEqual(concurrent.map(r=>r.status).sort(),[200,409]);checks++;
 const download=await request('/api/planning?download=1',200,{headers:owner});assert.match(download.headers.get('cache-control')??'',/no-store/);const exported=await download.json() as {total:{netWorth:string;feesPaid:string};score:{value:number}};assert.equal(exported.total.netWorth,'1000000');assert.equal(exported.total.feesPaid,'1234');checks+=3;
 const guestLibrary=await request('/api/community',200);assert.ok(!(await guestLibrary.text()).includes('PRIVATE_PLANNING_NAME'));checks++;
 await request('/api/community?mine=1',401);await request('/api/community?peers=1',401);
 await request('/api/community',404,post({action:'preview',id:runId,title:'A public title'},visitor));
 // Even a valid receipt cannot admit fictional practice data into this library.
 await request('/api/community',409,post({action:'preview',id:runId,title:'Fictional record blocked'}));
 const snapshot=await researchFixture();snapshot.asset.dataset.kind='historical';snapshot.benchmark.dataset.kind='historical';
 snapshot.asset.dataset.source='FICTIONAL_TEST_DECLARED_HISTORICAL_SOURCE';snapshot.benchmark.dataset.source='FICTIONAL_TEST_DECLARED_HISTORICAL_SOURCE';
 snapshot.asset.dataset.id=await datasetId(snapshot.asset.dataset);snapshot.benchmark.dataset.id=await datasetId(snapshot.benchmark.dataset);snapshot.config.assetId=snapshot.asset.dataset.id;snapshot.config.benchmarkId=snapshot.benchmark.dataset.id;
 const id=await researchFingerprint(snapshot),analysis=analyzeResearch(snapshot),created=new Date().toISOString(),run:SavedResearch={id,name:snapshot.config.name,created,symbol:snapshot.asset.dataset.symbol,benchmark:snapshot.benchmark.dataset.symbol,start:snapshot.config.start,end:snapshot.config.end,snapshot,analysis};
 await db.prepare('INSERT INTO research_runs (owner,id,name,created,symbol,benchmark,start,end,payload,result) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(owner['oai-authenticated-user-id'],id,run.name,created,run.symbol,run.benchmark,run.start,run.end,JSON.stringify(snapshot),JSON.stringify(analysis)).run();
 await request('/api/community',409,post({action:'preview',id,title:'Verified fixture template'}));
 // A server-owned receipt fixture tests authorization/binding, not a new live replay.
 const receipt={format:'marketlab-replay-receipt-v1',verified:true,reportId:id,reportDigest:await replayDigest(replayReportJSON(run)),verifiedAt:created,verifierVersion:REPLAY_VERSION,verifierSha256:'a'.repeat(64),segments:3,simulations:9,comparedFields:100,exactAccounting:true,floatAbsoluteTolerance:1e-10,floatRelativeTolerance:1e-10};
 await db.prepare('INSERT INTO research_replay_receipts (owner,run_id,receipt) VALUES (?,?,?)').bind(owner['oai-authenticated-user-id'],id,JSON.stringify(receipt)).run();
 const preview=await (await request('/api/community',200,post({action:'preview',id,title:'Verified fixture template'}))).json() as {digest:string;report:unknown};assert.ok(!JSON.stringify(preview).includes('FICTIONAL_TEST_DECLARED_HISTORICAL_SOURCE'));checks++;
 await request('/api/community',400,post({action:'publish',id,title:'Verified fixture template',digest:preview.digest,confirmed:false}));
 await request('/api/community',409,post({action:'publish',id,title:'Changed after consent',digest:preview.digest,confirmed:true}));
 const publication=await (await request('/api/community',201,post({action:'publish',id,title:'Verified fixture template',digest:preview.digest,confirmed:true}))).json() as {id:string};
 const listed=await (await request('/api/community',200)).json() as {publications:Record<string,unknown>[]};assert.equal(listed.publications.length,1);assert.ok(!('owner' in listed.publications[0]));assert.ok(!('report' in listed.publications[0]));checks+=3;
 const publicDetail=await (await request('/api/community?id='+publication.id,200)).json() as {report:{settings:{window:number}}};assert.equal(publicDetail.report.settings.window,snapshot.config.window);checks++;
 await request('/api/community',404,post({action:'unpublish',id:publication.id},visitor));
 await request('/api/community',200,post({action:'unpublish',id:publication.id}));await request('/api/community?id='+publication.id,404);
 // Consent and fixed-cohort suppression are exercised on isolated fictional rows.
 const period=priorQuarter(),peerHeaders=(i:number)=>({'oai-authenticated-user-id':`planning-peer-${i}`,'oai-authenticated-user-email':`peer${i}@marketlab.test`});
 for(let i=1;i<=19;i++)await db.prepare('INSERT INTO peer_contributions (owner,period,cohort,return_bps,created,active) VALUES (?,?,?,?,?,1)').bind(`planning-peer-${i}`,period.id,'target:moderate',1000,created).run();
 const hidden=await (await request('/api/community?peers=1',200,{headers:peerHeaders(1)})).json() as {release:unknown};assert.equal(hidden.release,null);checks++;
 const before=new Date(Date.parse(period.start+'T00:00:00Z')-86400000).toISOString().slice(0,10);
 const portfolio:PortfolioSnapshot={method:'historical-close-v1',name:'Fictional cash peer fixture',asOf:period.end,bindings:[],transactions:[{id:'fund',date:before,type:'deposit',symbol:'',units:'0',amount:'100000',fee:'0',reference:''}]};
 await db.prepare('INSERT INTO historical_portfolios (owner,revision,fingerprint,updated,payload) VALUES (?,1,?,?,?)').bind('planning-peer-20','b'.repeat(64),created,JSON.stringify(portfolio)).run();
 await request('/api/community',400,post({action:'peer-join',goal:'target',risk:'moderate',confirmed:false},peerHeaders(20)));
 await request('/api/community',400,post({action:'peer-join',goal:'arbitrary',risk:'moderate',confirmed:true},peerHeaders(20)));
 const joined=await (await request('/api/community',200,post({action:'peer-join',goal:'target',risk:'moderate',confirmed:true},peerHeaders(20)))).json() as {release:{medianReturnPct:number;participants:string;withdrawn:boolean}};
 assert.equal(joined.release.medianReturnPct,10);assert.equal(joined.release.participants,'20–49');checks+=2;
 await db.prepare('INSERT INTO peer_contributions (owner,period,cohort,return_bps,created,active) VALUES (?,?,?,?,?,1)').bind('planning-peer-21',period.id,'target:moderate',-5000,created).run();
 const frozen=await (await request('/api/community?peers=1',200,{headers:peerHeaders(20)})).json() as typeof joined;assert.deepEqual(frozen.release,joined.release);checks++;
 await request('/api/community',200,post({action:'peer-withdraw'},peerHeaders(20)));
 const after=await (await request('/api/community?peers=1',200,{headers:peerHeaders(1)})).json() as typeof joined;assert.equal(after.release.withdrawn,true);checks++;
 const tombstone=await db.prepare('SELECT active,return_bps FROM peer_contributions WHERE owner=? AND period=?').bind('planning-peer-20',period.id).first<{active:number;return_bps:number}>();assert.deepEqual(tombstone,{active:0,return_bps:0});checks++;
 await request('/api/community',409,post({action:'peer-join',goal:'target',risk:'higher',confirmed:true},peerHeaders(20)));
 await request('/api/support',401);await request('/api/support?inbox=1',403,{headers:visitor});
 const ticket=await (await request('/api/support',201,post({action:'create',subject:'Fictional support request',body:'This is a disposable support test.'},visitor))).json() as {id:string};
 const ownTickets=await (await request('/api/support',200,{headers:owner})).json() as {tickets:unknown[]};assert.equal(ownTickets.tickets.length,0);checks++;
 await request('/api/support',403,post({action:'reply',id:ticket.id,body:'Unauthorized reply'},visitor));
 await request('/api/support',200,post({action:'reply',id:ticket.id,body:'Fictional response saved for its author.'}));
 const replied=await (await request('/api/support',200,{headers:visitor})).json() as {tickets:{reply:string}[]};assert.equal(replied.tickets[0].reply,'Fictional response saved for its author.');checks++;
 for(const path of ['/trust','/status','/library','/support'])await request(path,200);
 const health=await (await request('/api/health',200)).json() as {status:string};assert.equal(health.status,'available');checks++;
 console.log(`Planning/community: ${checks} additional financial, consent, isolation, privacy suppression and support assertions passed.`);return checks;
}
