import { writeFile } from 'node:fs/promises';
import { datasetId } from '../lib/finance/market-data.ts';
import { researchFingerprint } from '../lib/finance/research.ts';
import { DEMO_COSTS, demoSnapshot } from '../lib/finance/quick-demo.ts';

const ids: Record<string,string> = {};
let dataset = '';
for(const cost of DEMO_COSTS){
  const snapshot=await demoSnapshot(cost.id);
  dataset=await datasetId(snapshot.asset.dataset);
  snapshot.asset.dataset.id=dataset;snapshot.benchmark.dataset.id=dataset;
  snapshot.config.assetId=dataset;snapshot.config.benchmarkId=dataset;
  ids[cost.id]=await researchFingerprint(snapshot);
}
const source=`// Generated by scripts/update-demo-fingerprints.ts; verified against inputs in unit tests.\n// Precomputed hashes let this fixed demo run even where browser Web Crypto is unavailable.\nexport const DEMO_DATASET_ID = '${dataset}';\nexport const DEMO_RUN_IDS = {\n${Object.entries(ids).map(([key,value])=>`  ${key}: '${value}',`).join('\n')}\n} as const;\n`;
await writeFile(new URL('../lib/finance/quick-demo-fingerprints.ts',import.meta.url),source);
console.log('Updated the fixed demo fingerprints. Run the unit and cross-language checks before publishing.');
