'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
type Ticket={id:string;subject:string;body:string;created:string;reply:string|null;replied:string|null};
export default function Support(){const [tickets,setTickets]=useState<Ticket[]>([]),[admin,setAdmin]=useState(false),[inbox,setInbox]=useState(false),[signedOut,setSignedOut]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(all=false){try{const r=await fetch('/api/support'+(all?'?inbox=1':''),{cache:'no-store'});if(r.status===401){setSignedOut(true);return;}const d=await r.json() as {tickets:Ticket[];admin:boolean;error?:string};if(!r.ok)throw new Error(d.error);setTickets(d.tickets);setAdmin(d.admin);}catch{setError('Support is temporarily unavailable. Please try again shortly.');}}
 useEffect(()=>{const c=new AbortController();void fetch('/api/support',{cache:'no-store',signal:c.signal}).then(async r=>{if(r.status===401){if(!c.signal.aborted)setSignedOut(true);return;}const d=await r.json() as {tickets:Ticket[];admin:boolean};if(!r.ok)throw new Error();if(!c.signal.aborted){setTickets(d.tickets);setAdmin(d.admin);}}).catch(()=>{if(!c.signal.aborted)setError('Support is temporarily unavailable. Please try again shortly.');});return()=>c.abort();},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>,id?:string){e.preventDefault();const form=e.currentTarget,fd=new FormData(form);setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(id?{action:'reply',id,body:fd.get('body')}:{action:'create',subject:fd.get('subject'),body:fd.get('body')})}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setMessage(id?'Reply saved. The user can read it here.':'Request received. Return here to read a reply.');form.reset();await load(inbox);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="public-product"><header><Link href="/" className="brand">MarketLab.</Link><Link href="/">My workspace</Link></header><h1>Support</h1><p className="public-intro">Report a problem, ask a question, or request help deleting your data. Replies appear here in your account.</p>{error&&<p className="error-banner" role="alert">{error}</p>}{message&&<p role="status" className="plan-insight">{message}</p>}{signedOut?<section className="panel plan-panel"><h2>Sign in to contact MarketLab</h2><p>Use your workspace account so your request and reply stay together.</p><Button asChild><Link href="/">Open sign-in</Link></Button></section>:<><form className="panel plan-panel plan-form" onSubmit={e=>void submit(e)}><h2>Contact MarketLab support</h2><p>Do not include passwords, API keys, bank account numbers or full financial statements.</p><fieldset disabled={busy}><div className="plan-fields"><label>Subject<Input name="subject" minLength={2} maxLength={100} required/></label></div><label>How can we help?<Textarea name="body" minLength={10} maxLength={3000} rows={5} required/></label><Button type="submit">{busy?'Saving…':'Send support request'}</Button></fieldset><p>Support is handled by the project owner. There is no guaranteed response time; this is not a channel for urgent trading or account-security instructions to a bank.</p></form>{admin&&<div className="plan-actions"><Button variant={inbox?'default':'outline'} onClick={()=>{setInbox(!inbox);void load(!inbox);}}>{inbox?'Show my requests':'Open support inbox'}</Button></div>}<section className="planning-space"><h2>{inbox?'Support inbox':'Your requests'}</h2>{tickets.length===0?<p>No requests yet.</p>:tickets.map(t=><article className="panel plan-panel" key={t.id}><h3>{t.subject}</h3><small>{new Date(t.created).toLocaleDateString()}</small><p className="support-message">{t.body}</p>{t.reply?<div className="plan-insight"><strong>MarketLab support</strong><p className="support-message">{t.reply}</p></div>:<p>Awaiting a reply.</p>}{inbox&&<form className="plan-form" onSubmit={e=>void submit(e,t.id)}><label>Reply<Textarea name="body" rows={3} minLength={2} maxLength={3000} required/></label><Button disabled={busy} type="submit">Send reply in app</Button></form>}</article>)}</section></>}<footer><Link href="/trust">Privacy & trust</Link><Link href="/status">Status</Link></footer></main>;
}
